#!/usr/bin/env python3
"""Generate contracts/manifest.json and contracts/types.ts — the catalogue an API server reads first.

The manifest answers, for one entity: what is it called, where does its data live, how are records
packed in those files, which field is its stable address, which namespace does that address use, how
many records exist, and which schema validates it. That is everything a server needs to mount
`/kanji/:id` without knowing anything else about the project.

types.ts is the same contract for a TypeScript client. It is GENERATED from the schemas, so an
interface cannot drift from the data the way a hand-written one does — the prototype's own RawItem
declared `ai?: number` for months after the field had been renamed, and nothing caught it because
only the bundler knew.

Reads:  contracts/*.schema.json
Writes: contracts/manifest.json, contracts/types.ts
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
ROOT = Path(__file__).resolve().parents[2]
CONTRACTS = ROOT / "contracts"

TS_HEADER = """// GENERATED by scripts/contracts/build_manifest.py from contracts/*.schema.json — do not edit.
//
// The corpus is private paid content. These are TYPES only; importing them pulls in no data, and the
// JSON they describe must never reach a client bundle (see prototype/README.md on the SSR-only rule).

/** Learner-facing prose, per locale. pt-BR is always present; `en` is the Layer-A source when there was one. */
export interface LocaleText { "pt-BR": string; en?: string; [locale: string]: string | undefined }

/** Like LocaleText for fields that are plural in every locale (a kanji's meanings, a sense's glosses). */
export interface LocaleTextList { "pt-BR": string[]; en?: string[]; [locale: string]: string[] | undefined }

/** A prefixed stable id: "kanji:食", "vocab:1580640", "les:n5-saudacoes-01". */
export type StableId = string;

export type Level = "pre-n5" | "n5" | "n4" | "n3" | "n2" | "n1";

/** A = authoritative (zero AI) · B = derived and machine-verified · C = pedagogy, needs a teacher. */
export type Layer = "A" | "B" | "C";
"""

SCALAR = {"string": "string", "integer": "number", "number": "number",
          "boolean": "boolean", "null": "null"}


def ts_name(entity: str) -> str:
    return "".join(p.capitalize() for p in entity.split("_"))


def ts_type(node: dict, depth: int = 0) -> str:
    """Render one schema node as a TypeScript type."""
    ref = node.get("$ref")
    if ref:
        tail = ref.split("/")[-1]
        if tail in ("LocaleText", "LocaleTextList", "StableId", "Level", "Layer"):
            return tail
        if tail in ("needs_review", "ai_generated"):
            return "boolean"
        if tail == "source":
            return "string"
        if tail == "level_confidence":
            return "number | null"
        if tail in ("level_agreement",):
            return "string | null"
        if tail == "level_sources":
            return "Record<string, unknown> | null"
        return "unknown"

    if "anyOf" in node:
        return " | ".join(dict.fromkeys(ts_type(x, depth) for x in node["anyOf"]))

    t = node.get("type")
    if isinstance(t, list):
        return " | ".join(dict.fromkeys(
            ts_type({**node, "type": one}, depth) for one in t))

    if t == "array":
        return f"{ts_type(node.get('items', {}), depth + 1)}[]"

    if t == "object" or "properties" in node:
        props = node.get("properties")
        if not props:
            return "Record<string, unknown>"
        req = set(node.get("required", []))
        pad = "  " * (depth + 2)
        fields = []
        for k, v in props.items():
            key = k if k.isidentifier() else json.dumps(k)
            fields.append(f"{pad}{key}{'' if k in req else '?'}: {ts_type(v, depth + 1)};")
        close = "  " * (depth + 1)
        return "{\n" + "\n".join(fields) + f"\n{close}}}"

    if "enum" in node and all(isinstance(x, str) or x is None for x in node["enum"]):
        return " | ".join("null" if x is None else json.dumps(x) for x in node["enum"])

    return SCALAR.get(t, "unknown")


def namespaces_of(glob: str | None, packing: str, id_field: str | None):
    """Every prefix actually used by this entity's addresses, e.g. ["cf", "gf", "kr", ...]."""
    if not glob:
        return None
    found: set[str] = set()
    for path in sorted(ROOT.glob(glob)):
        data = json.loads(path.read_text(encoding="utf-8"))
        if packing == "map":
            keys = list(data) if isinstance(data, dict) else []
        elif packing == "single":
            keys = [data.get(id_field)] if id_field and isinstance(data, dict) else []
        else:
            keys = [r.get(id_field) for r in data
                    if id_field and isinstance(r, dict)] if isinstance(data, list) else []
        for k in keys:
            if isinstance(k, str) and ":" in k:
                found.add(k.split(":", 1)[0])
        if len(found) > 24:            # exam items carry one prefix per section; that is enough
            break
    return sorted(found) or None


def main() -> int:
    schemas = sorted(p for p in CONTRACTS.glob("*.schema.json") if p.name != "common.schema.json")
    if not schemas:
        print("no schemas — run build_schemas.py first", file=sys.stderr)
        return 2

    entities, ts_blocks = [], []
    for path in schemas:
        doc = json.loads(path.read_text(encoding="utf-8"))
        meta = doc.get("x-yomineko", {})
        entity = meta.get("entity", path.name.split(".")[0])
        id_field = meta.get("stable_id_field")
        # The namespace is read off the DATA rather than off the schema: the generated schemas point
        # `id`/`slug` at the shared StableId definition, whose pattern is deliberately generic, so the
        # schema alone cannot say that kanji ids start with "kanji:" and exam items with "cf:"/"kr:"/…
        namespace = namespaces_of(meta.get("glob"), meta.get("packing", "list"), id_field)             or meta.get("key_namespace")
        # Four entities have no stable id at all: the three stroke sets are addressed by the character
        # they draw, and the two keyed files by their key. Recording the natural key is honest about
        # the gap — an API can still route on it, but these records cannot be linked to from the graph
        # the way every other record can.
        natural = None
        if not id_field and meta.get("packing") != "map":
            for cand in ("character", "char"):
                if cand in doc.get("properties", {}):
                    natural = cand
                    break
        entities.append({
            "entity": entity,
            "title": doc.get("title", entity),
            "description": doc.get("description", ""),
            "schema": path.name,
            "files": meta.get("glob"),
            "packing": meta.get("packing", "list"),
            "stable_id_field": id_field,
            "id_namespace": namespace or meta.get("key_namespace"),
            "natural_key": natural,
            "records": meta.get("records"),
        })

        name = ts_name(entity)
        desc = doc.get("description", "").strip()
        block = []
        if desc:
            block.append("/** " + desc + " */")
        props = doc.get("properties", {})
        if props:
            req = set(doc.get("required", []))
            block.append(f"export interface {name} {{")
            for k, v in props.items():
                key = k if k.isidentifier() else json.dumps(k)
                block.append(f"  {key}{'' if k in req else '?'}: {ts_type(v, 0)};")
            block.append("}")
        else:
            block.append(f"export type {name} = {ts_type(doc, 0)};")
        ts_blocks.append("\n".join(block))

    manifest = {
        "schema_version": "1.0",
        "note": "The catalogue of every corpus and courseware entity: where its data lives, how the "
                "records are packed, and which field is its public address. An API mounts its routes "
                "from this. Generated by scripts/contracts/build_manifest.py; validated by "
                "scripts/validate/validate_contracts.py.",
        "id_convention": "Every record is addressed by a prefixed stable id — <namespace>:<identifier>. "
                         "Some registries also carry an integer `id`; that is a storage row number, it "
                         "is NOT stable across a rebuild, and it must never be used as an API key.",
        "common_schema": "common.schema.json",
        "types": "types.ts",
        "entities": sorted(entities, key=lambda e: e["entity"]),
    }
    (CONTRACTS / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (CONTRACTS / "types.ts").write_text(
        TS_HEADER + "\n" + "\n\n".join(ts_blocks) + "\n", encoding="utf-8")

    total = sum(e["records"] or 0 for e in entities)
    print(f"{len(entities)} entities, {total} records -> contracts/manifest.json + contracts/types.ts")
    for e in manifest["entities"]:
        print(f"  {e['entity']:22} {str(e['records'] or ''):>6}  id={e['stable_id_field'] or '(key)':<6} "
              f"ns={','.join(e['id_namespace']) if e['id_namespace'] else '-'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
