#!/usr/bin/env python3
"""Generate contracts/manifest.json and contracts/types.ts — the catalogue an API server reads first.

The manifest answers, for one entity: what is it called, where does its data live, how are records
packed in those files, which field is its stable address, which namespace does that address use, how
many records exist, and which schema validates it. That is everything a server needs to mount
`/kanji/:id` without knowing anything else about the project.

types.ts is the same contract for a TypeScript client. It is GENERATED from the schemas, so an
interface cannot drift from the data the way a hand-written one does — the prototype's own RawItem
declared `ai?: number` for months after the field had been renamed, and nothing caught it because
only the bundler knew.

Entities come in two CLASSES, declared per schema in x-yomineko.class:

  content  — committed JSON under corpus/ or course/. `files` is a glob that matches and `records` is
             an exact count. 23 of them, flat in contracts/.
  runtime  — a contract with no committed records: user state, minted per learner by the app. `files`
             and `records` are null, and that is correct rather than a stopped exporter. 7 of them,
             under contracts/user_state/, specified by design/user_state.md.

Reads:  contracts/*.schema.json, contracts/*/*.schema.json
Writes: contracts/manifest.json, contracts/types.ts
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
ROOT = Path(__file__).resolve().parents[2]
CONTRACTS = ROOT / "contracts"

# The exporters pin their one wall-clock stamp through build_date() so a rebuild reproduces; the
# manifest's release identity is the same stamp for the same reason.
sys.path.append(str(ROOT / "scripts"))
from dbtarget import build_date  # noqa: E402

TS_HEADER = """// GENERATED by scripts/contracts/build_manifest.py from contracts/*.schema.json — do not edit.
//
// The corpus is private paid content. These are TYPES only; importing them pulls in no data, and the
// JSON they describe must never reach a client bundle (see prototype/README.md on the SSR-only rule).

/** Learner-facing prose, per locale. pt-BR is always present; `en` is the Layer-A source when there was one. */
export interface LocaleText { "pt-BR": string; en?: string; [locale: string]: string | undefined }

/** Like LocaleText for fields that are plural in every locale (a kanji's meanings, a sense's glosses). */
export interface LocaleTextList { "pt-BR": string[]; en?: string[]; [locale: string]: string[] | undefined }

/** A prefixed stable id: "kanji:食", "vocab:1580640", "les:n5-saudacoes-01". */
export type StableId = string;

export type Level = "pre-n5" | "n5" | "n4" | "n3" | "n2" | "n1";

/** A = authoritative (zero AI) · B = derived and machine-verified · C = pedagogy, needs a teacher. */
export type Layer = "A" | "B" | "C";
"""

SCALAR = {"string": "string", "integer": "number", "number": "number",
          "boolean": "boolean", "null": "null"}


def ts_name(entity: str) -> str:
    return "".join(p.capitalize() for p in entity.split("_"))


def ts_type(node: dict, depth: int = 0, defs: dict | None = None, seen: frozenset = frozenset()) -> str:
    """Render one schema node as a TypeScript type.

    `defs` is the owning document's `$defs` block. A local `#/$defs/<name>` reference is inlined from
    it rather than falling through to `unknown`: a schema that factors a value set out into `$defs`
    (exam_attempt's fourteen paper sections) would otherwise reach types.ts as `unknown`, which is
    precisely the silent drift this generator exists to prevent. `seen` breaks a recursive $def.
    """
    ref = node.get("$ref")
    if ref:
        if ref.startswith("#/$defs/") and defs is not None:
            name = ref.split("/")[-1]
            if name in defs and name not in seen:
                return ts_type(defs[name], depth, defs, seen | {name})
        tail = ref.split("/")[-1]
        if tail in ("LocaleText", "LocaleTextList", "StableId", "Level", "Layer"):
            return tail
        if tail == "Locale":
            return "string"
        if tail in ("IdRef",):
            return "StableId"
        if tail == "IdRefList":
            return "StableId[]"
        if tail == "LevelSources":
            return "Record<string, unknown> | null"
        if tail in ("needs_review", "ai_generated"):
            return "boolean"
        if tail == "source":
            return "string"
        if tail == "level_confidence":
            return "number | null"
        if tail in ("level_agreement",):
            return "string | null"
        if tail == "level_sources":
            return "Record<string, unknown> | null"
        return "unknown"

    if "anyOf" in node:
        return " | ".join(dict.fromkeys(ts_type(x, depth, defs, seen) for x in node["anyOf"]))

    t = node.get("type")
    if isinstance(t, list):
        return " | ".join(dict.fromkeys(
            ts_type({**node, "type": one}, depth, defs, seen) for one in t))

    if t == "array":
        return f"{ts_type(node.get('items', {}), depth + 1, defs, seen)}[]"

    if t == "object" or "properties" in node:
        props = node.get("properties")
        if not props:
            return "Record<string, unknown>"
        req = set(node.get("required", []))
        pad = "  " * (depth + 2)
        fields = []
        for k, v in props.items():
            key = k if k.isidentifier() else json.dumps(k)
            fields.append(f"{pad}{key}{'' if k in req else '?'}: {ts_type(v, depth + 1, defs, seen)};")
        close = "  " * (depth + 1)
        return "{\n" + "\n".join(fields) + f"\n{close}}}"

    if "enum" in node and all(isinstance(x, str) or x is None for x in node["enum"]):
        return " | ".join("null" if x is None else json.dumps(x) for x in node["enum"])

    return SCALAR.get(t, "unknown")


def ts_interface(entity: str, doc: dict) -> str:
    """One entity's TypeScript declaration, from its schema's root properties."""
    name = ts_name(entity)
    desc = doc.get("description", "").strip()
    block = []
    if desc:
        block.append("/** " + desc + " */")
    defs = doc.get("$defs", {})
    props = doc.get("properties", {})
    if props:
        req = set(doc.get("required", []))
        block.append(f"export interface {name} {{")
        for k, v in props.items():
            key = k if k.isidentifier() else json.dumps(k)
            block.append(f"  {key}{'' if k in req else '?'}: {ts_type(v, 0, defs)};")
        block.append("}")
    else:
        block.append(f"export type {name} = {ts_type(doc, 0, defs)};")
    return "\n".join(block)


def namespaces_of(glob: str | None, packing: str, id_field: str | None):
    """Every prefix actually used by this entity's addresses, e.g. ["cf", "gf", "kr", ...]."""
    if not glob:
        return None
    found: set[str] = set()
    for path in sorted(ROOT.glob(glob)):
        data = json.loads(path.read_text(encoding="utf-8"))
        if packing == "map":
            keys = list(data) if isinstance(data, dict) else []
        elif packing == "single":
            keys = [data.get(id_field)] if id_field and isinstance(data, dict) else []
        else:
            keys = [r.get(id_field) for r in data
                    if id_field and isinstance(r, dict)] if isinstance(data, list) else []
        for k in keys:
            if isinstance(k, str) and ":" in k:
                found.add(k.split(":", 1)[0])
        if len(found) > 24:            # exam items carry one prefix per section; that is enough
            break
    return sorted(found) or None




# ==================================================================================================
# release identity (W06)
# ==================================================================================================
# The catalogue said WHAT exists and never WHICH VERSION of it. Two exports of a corpus mid-campaign
# are the same 23 entities with the same record counts and different content, and nothing in
# contracts/ could tell them apart — so an approval, a bug report or a prototype sync had no build to
# name. `build` fixes exactly that and nothing more:
#
#   date       — the export date, through build_date() ($YOMINEKO_BUILD_DATE), so a rebuild reproduces
#   git_head   — the commit the build was cut from, read straight out of .git (never by running git,
#                which is not available to every consumer of this generator)
#   entities   — one content hash per entity, over the BYTES of the files its glob matches, in glob
#                order, each file's own digest folded in with its repo-relative path so a rename is a
#                change. This is what makes "the same corpus" checkable.
#
# validate_schema_generation_is_current.py compares this block like everything else EXCEPT `date` and
# `git_head`: those two legitimately differ between the committed manifest and a fresh regeneration on
# another day or another commit, while a per-entity hash that has moved means the DATA moved and the
# manifest is stale. A hash is null only where the entity declares no glob (the runtime class).
def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def entity_content_hash(glob: str | None) -> str | None:
    """One digest over everything this entity's glob matches, path-sensitive and order-stable."""
    if not glob:
        return None
    outer = hashlib.sha256()
    for path in sorted(ROOT.glob(glob)):
        if not path.is_file():
            continue
        outer.update(path.relative_to(ROOT).as_posix().encode("utf-8"))
        outer.update(b"\0")
        outer.update(_sha256_file(path).encode("ascii"))
        outer.update(b"\n")
    return outer.hexdigest()


def git_head() -> str | None:
    """The commit this build was cut from, by READING .git — no subprocess, no git on PATH required.

    A detached HEAD holds the sha directly; otherwise it names a ref, which is either a loose file or
    an entry in packed-refs. Returns None when any of that is missing, because a tarball with no .git
    is a legitimate way to consume this repo and must not fail the generator.
    """
    head = ROOT / ".git" / "HEAD"
    if not head.is_file():
        return None
    try:
        text = head.read_text(encoding="utf-8").strip()
    except OSError:
        return None
    if not text.startswith("ref:"):
        return text or None
    ref = text.split(":", 1)[1].strip()
    loose = ROOT / ".git" / ref
    if loose.is_file():
        return loose.read_text(encoding="utf-8").strip() or None
    packed = ROOT / ".git" / "packed-refs"
    if packed.is_file():
        for line in packed.read_text(encoding="utf-8").splitlines():
            if line.startswith("#") or not line.strip():
                continue
            parts = line.split()
            if len(parts) == 2 and parts[1] == ref:
                return parts[0]
    return None


def main() -> int:
    # Content entities are flat in contracts/; the runtime class (contracts/user_state/) is one level
    # down, so the glob has to descend exactly one directory. `sorted` over the relative POSIX path
    # keeps the output stable across platforms.
    schemas = sorted((p for p in [*CONTRACTS.glob("*.schema.json"), *CONTRACTS.glob("*/*.schema.json")]
                      if p.name != "common.schema.json"),
                     key=lambda p: p.relative_to(CONTRACTS).as_posix())
    if not schemas:
        print("no schemas — run build_schemas.py first", file=sys.stderr)
        return 2

    entities, ts_blocks = [], []
    for path in schemas:
        doc = json.loads(path.read_text(encoding="utf-8"))
        meta = doc.get("x-yomineko", {})
        entity = meta.get("entity", path.name.split(".")[0])
        id_field = meta.get("stable_id_field")
        # Entity CLASS. `content` = committed JSON under corpus/ or course/, located by a glob and
        # counted exactly. `runtime` = a contract with no committed records and no glob, because the
        # records are minted per learner by the app (design/user_state.md §12). The class is DECLARED
        # in the schema, never inferred from a missing glob: an exporter that stopped also produces a
        # missing glob, and the two must not look the same to a validator.
        cls = meta.get("class", "content")
        if cls == "runtime":
            # `files`, `packing` and `records` are reported as DECLARED, not normalized to null. A
            # runtime schema that declares a glob is a contradiction, and the catalogue's job is to
            # show it so validate_schema_generation_is_current.py can fail on it — a generator that
            # quietly wrote null here would launder the very mistake the class exists to catch.
            entities.append({
                "entity": entity,
                "class": cls,
                "title": doc.get("title", entity),
                "description": doc.get("description", ""),
                "schema": path.relative_to(CONTRACTS).as_posix(),
                "files": meta.get("glob"),
                "packing": meta.get("packing"),
                "stable_id_field": id_field,
                "id_namespace": meta.get("key_namespace"),
                "natural_key": meta.get("natural_key"),
                "records": meta.get("records"),
            })
            ts_blocks.append(ts_interface(entity, doc))
            continue
        # The namespace is read off the DATA rather than off the schema: the generated schemas point
        # `id`/`slug` at the shared StableId definition, whose pattern is deliberately generic, so the
        # schema alone cannot say that kanji ids start with "kanji:" and exam items with "cf:"/"kr:"/…
        namespace = namespaces_of(meta.get("glob"), meta.get("packing", "list"), id_field)             or meta.get("key_namespace")
        # Four entities have no stable id at all: the three stroke sets are addressed by the character
        # they draw, and the two keyed files by their key. Recording the natural key is honest about
        # the gap — an API can still route on it, but these records cannot be linked to from the graph
        # the way every other record can.
        natural = meta.get("natural_key")
        if natural is None and not id_field and meta.get("packing") != "map":
            for cand in ("character", "char"):
                if cand in doc.get("properties", {}):
                    natural = cand
                    break
        entities.append({
            "entity": entity,
            "class": cls,
            "title": doc.get("title", entity),
            "description": doc.get("description", ""),
            "schema": path.relative_to(CONTRACTS).as_posix(),
            "files": meta.get("glob"),
            "packing": meta.get("packing", "list"),
            "stable_id_field": id_field,
            "id_namespace": namespace or meta.get("key_namespace"),
            "natural_key": natural,
            "records": meta.get("records"),
        })
        ts_blocks.append(ts_interface(entity, doc))

    manifest = {
        "schema_version": "1.0",
        "note": "The catalogue of every corpus and courseware entity: where its data lives, how the "
                "records are packed, and which field is its public address. An API mounts its routes "
                "from this. Generated by scripts/contracts/build_manifest.py; validated by "
                "scripts/validate/validate_contracts.py.",
        "id_convention": "Every record is addressed by a prefixed stable id — <namespace>:<identifier>. "
                         "Some registries also carry an integer `id`; that is a storage row number, it "
                         "is NOT stable across a rebuild, and it must never be used as an API key.",
        "classes": {
            "content": "Committed JSON under corpus/ or course/. `files` is a glob that matches and "
                       "`records` is an exact count; an entity whose glob matches zero records is a "
                       "FAILURE, not an empty entity.",
            "runtime": "A contract with no committed records and no `files` glob, because the records "
                       "are minted per learner by the app — user state, not corpus content. `files` "
                       "and `records` are null and that is CORRECT. The class is declared in the "
                       "schema's x-yomineko block, never inferred from an absent glob, so a content "
                       "entity whose exporter stopped cannot relabel itself and go quiet. "
                       "Specified by design/user_state.md.",
        },
        "common_schema": "common.schema.json",
        "types": "types.ts",
        "build": {
            "note": "Release identity. `date` and `git_head` say WHEN and FROM WHAT this "
                    "catalogue was cut; `entities` is one content hash per entity over the bytes "
                    "its glob matches, so two builds of the same 23 entities with different "
                    "content are distinguishable. Approvals in "
                    "research/derived/review_ledger.json are anchored per record, not per build; "
                    "this is the build-level companion to that. Regenerate with "
                    "scripts/contracts/build_manifest.py after every export.",
            "date": build_date(),
            "git_head": git_head(),
            "entities": {e["entity"]: entity_content_hash(e.get("files"))
                         for e in sorted(entities, key=lambda e: e["entity"])},
        },
        "entities": sorted(entities, key=lambda e: (e["class"] != "content", e["entity"])),
    }
    (CONTRACTS / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (CONTRACTS / "types.ts").write_text(
        TS_HEADER + "\n" + "\n\n".join(ts_blocks) + "\n", encoding="utf-8")

    hashed = sum(1 for v in manifest["build"]["entities"].values() if v)
    total = sum(e["records"] or 0 for e in entities)
    n_runtime = sum(1 for e in entities if e["class"] == "runtime")
    print(f"{len(entities)} entities ({len(entities) - n_runtime} content, {n_runtime} runtime), "
          f"{total} records -> contracts/manifest.json + contracts/types.ts")
    print(f"  build {manifest['build']['date']} @ "
          f"{(manifest['build']['git_head'] or '(no .git)')[:12]} — {hashed} entity content "
          f"hashes")
    for e in manifest["entities"]:
        count = "runtime" if e["class"] == "runtime" else str(e["records"] or "")
        ns = e["id_namespace"]
        print(f"  {e['entity']:22} {count:>7}  id={e['stable_id_field'] or '(key)':<6} "
              f"ns={','.join(ns) if isinstance(ns, list) else (ns or '-')}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
