// GENERATED by scripts/contracts/build_manifest.py from contracts/*.schema.json — do not edit.
//
// The corpus is private paid content. These are TYPES only; importing them pulls in no data, and the
// JSON they describe must never reach a client bundle (see prototype/README.md on the SSR-only rule).

/** Learner-facing prose, per locale. pt-BR is always present; `en` is the Layer-A source when there was one. */
export interface LocaleText { "pt-BR": string; en?: string; [locale: string]: string | undefined }

/** Like LocaleText for fields that are plural in every locale (a kanji's meanings, a sense's glosses). */
export interface LocaleTextList { "pt-BR": string[]; en?: string[]; [locale: string]: string[] | undefined }

/** A prefixed stable id: "kanji:食", "vocab:1580640", "les:n5-saudacoes-01". */
export type StableId = string;

export type Level = "pre-n5" | "n5" | "n4" | "n3" | "n2" | "n1";

/** A = authoritative (zero AI) · B = derived and machine-verified · C = pedagogy, needs a teacher. */
export type Layer = "A" | "B" | "C";

/** Something a learner can DO once a set of lessons is complete. The bridge between the syllabus and the exam. */
export interface Capability {
  grammar_keys: string[];
  id: StableId;
  level: Level;
  name: LocaleText;
}

/** Which capabilities each lesson contributes to. A keyed collection rather than a record list: the lesson id IS the key, so there is no id field inside the value. Hand-authored — a map's contract is about its key space and value shape, which the record-shape generator has no idiom for. */
export type CapabilityLessonMap = Record<string, unknown>;

/** The full inflection table for one verb or adjective. It is addressed by the vocab entry it belongs to, so `slug` here is a foreign key into vocab, not a new address. */
export interface Conjugation {
  class: "godan" | "i_adj" | "ichidan" | "kuru_irregular" | "na_adj" | "suru_irregular";
  conjugations: {
      form?: "adverbial" | "attributive" | "causative" | "causative_passive" | "conditional_ba" | "conditional_tara" | "dictionary" | "imperative" | "masu" | "masu_negative" | "masu_past" | "masu_past_negative" | "negative" | "negative_te" | "passive" | "past" | "past_negative" | "polite" | "polite_negative" | "polite_past" | "potential" | "te" | "volitional" | "volitional_polite";
      kana?: string;
      romaji?: string;
      surface?: string;
    }[];
  headword: string;
  kana: string;
  kind: "adjective" | "verb";
  level: Level;
  slug: StableId;
  vocab_id: number;
}

/** A course root for one level: its ordered topics and the overview shown before the first lesson. */
export interface Course {
  id: StableId;
  level: Level;
  order: number;
  overview: LocaleText;
  title: LocaleText;
  topics: {
      id?: StableId;
      lesson_count?: number;
      order?: number;
      path?: string;
      theme?: string;
      title?: LocaleText;
      unlocks_summary?: {
        grammar?: number;
        kanji?: number;
        vocab?: number;
      };
    }[];
}

/** The index an API reads first: every course, where its root lives, and how much is in it. */
export interface CourseManifest {
  courses: {
      id?: StableId;
      lesson_count?: number;
      level?: Level;
      order?: number;
      path?: string;
      title?: LocaleText;
      topic_count?: number;
    }[];
  enums_ref: string;
  generated: string;
  schema_version: string;
}

/** One JLPT-style practice question, drawn from the corpus so every item is also findable in a lesson. The id prefix names the section, and each section has its own required shape. */
export interface ExamItem {
  ai_generated: boolean;
  answer?: string;
  audio?: string;
  correct?: string;
  distractors?: string[];
  grammar?: string;
  id: StableId;
  layer: Layer;
  level: Level;
  needs_review: boolean;
  pieces?: string[];
  question?: string;
  reading?: string;
  script?: {
      speaker?: "F1" | "F2" | "M1" | "M2" | "N";
      text?: string;
    }[];
  sentence?: string;
  source: string;
  stem?: string;
  target?: string;
  vocab?: string;
  vocab_id?: number;
  wrong?: string[];
}

/** One generated conjugation drill: a prompt form, the correct inflection, and three distractors. */
export interface ExerciseConjugation {
  class: "godan" | "i_adj" | "ichidan" | "kuru_irregular" | "na_adj" | "suru_irregular";
  correct: string;
  distractors: string[];
  example: string | null;
  form: "adverbial" | "attributive" | "causative" | "causative_passive" | "conditional_ba" | "conditional_tara" | "dictionary" | "imperative" | "masu" | "masu_negative" | "masu_past" | "masu_past_negative" | "negative" | "negative_te" | "passive" | "past" | "past_negative" | "polite" | "polite_negative" | "polite_past" | "potential" | "te" | "volitional" | "volitional_polite";
  form_label: LocaleText;
  headword: string;
  id: StableId;
  kana: string;
  kind: "adjective" | "verb";
  layer: Layer;
  level: Level;
  needs_review: boolean;
  prompt: string;
  romaji: string;
  slug: StableId;
  source: string;
  vocab_id: number;
}

/** One generated particle-role drill, derived mechanically from a sentence's own particles. */
export interface ExerciseRole {
  correct: string;
  distractors: string[];
  id: StableId;
  jp: string;
  layer: Layer;
  level: Level;
  needs_review: boolean;
  particle: string | null;
  prompt: LocaleText;
  role: "direction" | "from" | "modifier" | "object" | "predicate" | "subject" | "topic";
  sentence: string;
  source: string;
}

/** A group of items that behave alike (a conjugation class, a particle set, a semantic field), with the rule that governs the group. */
export interface Family {
  description?: LocaleText | null;
  governing_rule: LocaleText | null;
  id: number;
  importance_rank: number;
  label: LocaleText;
  members: {
      id?: number;
      intra_order?: number;
      is_core?: boolean;
      member_type?: "grammar" | "kanji" | "vocab";
      note?: LocaleText | null;
      ref?: string;
      slug?: StableId;
    }[];
  slug: StableId;
  spans_levels: Level[];
  type: "conjugation_class" | "contrast_pair" | "function_set" | "kanji_component" | "particle_set" | "phonetic_series" | "semantic_field" | "word_family";
}

/** One grammar point: its forms, how it is formed, what it contrasts with, and the pedagogy around it. */
export interface Grammar {
  caution: "none" | "offensive" | "rough" | "sensitive" | null;
  explanation: LocaleText;
  families: string[];
  formation: LocaleText;
  formation_steps: {
    variants?: {
        base?: "any" | "clause" | "i-adjective" | "na-adjective" | "noun" | "verb";
        example?: string;
        steps?: unknown[];
      }[];
  };
  forms: {
      form?: string;
      meaning?: LocaleText | null;
    }[];
  id: number;
  key: string;
  label: LocaleText;
  level: Level;
  level_agreement: string | null;
  level_confidence: number | null;
  level_sources: Record<string, unknown> | null;
  needs_review: boolean;
  nuance: LocaleText;
  nuance_tags: string[];
  refs: {
    also_known_as?: string[];
    label_en?: string;
    level_sources?: Record<string, unknown> | null;
  };
  register: "casual" | "colloquial" | "dated" | "feminine" | "formal" | "honorific" | "humble" | "literary" | "masculine" | "neutral" | "plain" | "polite" | "slang" | "written"[];
  related: string[];
  slug: StableId;
  steps_unavailable: string | null;
  structure_pattern: string;
  usage_contexts: string[];
}

/** One hiragana or katakana character and the family it belongs to. */
export interface Kana {
  char: string;
  family: string;
  family_label: LocaleText;
  id: StableId;
  romaji: string;
  type: "base" | "dakuten" | "handakuten" | "long-vowel" | "sokuon" | "yoon";
}

/** The kana chart as ordered groups. Keyed by script, so unlike the capability map its keys are a fixed enum rather than stable IDs — which is why the two map-packed files cannot share one generated shape. The script is not just a label: every id under `hiragana` must be a hiragana id, and the per-script patternProperties below are what ties the two together, so a katakana glyph filed under the wrong script fails instead of validating. */
export type KanaFamily = Record<string, unknown>;

/** One kanji character: readings, meanings, radical decomposition and the level it is taught at. Layer A apart from the pt-BR meanings. */
export interface Kanji {
  character: string;
  components: string[];
  example_sentences: string[];
  example_words: {
      gloss?: LocaleTextList;
      headword?: string;
      kana?: string;
      slug?: StableId;
      vocab_id?: number;
    }[];
  families: string[];
  freq_rank: number | null;
  grade: number;
  id: number;
  irregular_note: LocaleText | null;
  kangxi_radical: number;
  kanjivg_ref: string;
  level: Level;
  level_agreement: string | null;
  level_confidence: number | null;
  level_sources: Record<string, unknown> | null;
  meanings: LocaleTextList;
  notes?: LocaleText | null;
  radical_char: string;
  readings: {
      common?: boolean;
      example_vocab?: string[];
      example_vocab_ids?: number[] | null;
      introduced_at_level?: Level | null;
      note?: LocaleText | null;
      okurigana?: string | null;
      reading?: string;
      type?: "kun" | "nanori" | "on";
    }[];
  slug: StableId;
  strokes: number;
  unicode: string;
}

/** The leaf unit a learner sits down to. Holds objectives, explanation, exercises and the items it introduces — all corpus content by REFERENCE, never embedded. */
export interface Lesson {
  body: string;
  cumulative_known_set: {
    "conjugation-form": unknown[];
    grammar: string[];
    "kana-family": string[];
    kanji: string[];
    phrase: unknown[];
    vocab: string[];
  };
  description: LocaleText;
  exercises: {
      answer?: {
        accept?: unknown[];
        choices?: unknown[];
        correct?: string;
        full?: string;
        order?: unknown[];
        pairs?: unknown[];
        sentence_refs?: unknown[];
        text?: string;
      };
      explanation?: LocaleText;
      id?: StableId;
      prompt?: LocaleText;
      sentence_refs?: string[];
      type?: "cloze" | "handwriting" | "listening" | "matching" | "ordering" | "particle_choice" | "production" | "reading" | "recognition" | "sentence_build";
    }[];
  feature_unlocks: "feat:conjugation-drill" | "feat:find-correct-kanji" | "feat:find-correct-particle" | "feat:furigana-toggle" | "feat:handwriting-input" | "feat:jlpt-sim-n4" | "feat:jlpt-sim-n5" | "feat:kana-input" | "feat:kanji-lookup" | "feat:listening" | "feat:particle-drill" | "feat:phrase-builder" | "feat:romaji-toggle" | "feat:srs-reviews" | "feat:visual-novel" | "feat:voice-mode"[];
  id: StableId;
  level: Level;
  needs: unknown[];
  needs_review: boolean;
  objectives: LocaleText[];
  order: number;
  schema_version: string;
  sentence_refs: string[];
  srs: {
    introduces_cards: {
        card_types?: unknown[];
        deck?: "deck:grammar-n3" | "deck:grammar-n4" | "deck:grammar-n5" | "deck:kana-hiragana" | "deck:kana-katakana" | "deck:kanji-n3" | "deck:kanji-n4" | "deck:kanji-n5" | "deck:phrases" | "deck:vocab-n3" | "deck:vocab-n4" | "deck:vocab-n5";
        item?: string;
      }[];
  };
  title: LocaleText;
  topic: string;
  unlocks: {
      ref?: string;
      type?: "conjugation-form" | "feature" | "grammar" | "kana-family" | "kanji" | "kanji-family" | "phrase" | "srs-deck" | "vocab";
    }[];
}

/** A short reading passage gated to a lesson, with its tokens and translation. */
export interface Reading {
  ai_generated: boolean;
  gated_to_lesson: string;
  jp: string;
  layer: Layer;
  length_band: "long" | "paragraph" | "short";
  level: Level;
  needs_review: boolean;
  slug: StableId;
  source_slugs: string[];
  title: LocaleText;
  tokens: {
      pos?: "adnominal" | "adverb" | "auxiliary" | "conjunction" | "filler" | "i-adjective" | "interjection" | "na-adjective" | "noun" | "numeral" | "particle" | "prefix" | "pronoun" | "punctuation" | "suffix" | "symbol" | "verb" | "whitespace";
      r?: string;
      ro?: string;
      s?: string;
    }[];
  translation: LocaleText;
  uses: {
    kanji: string[];
    vocab: string[];
  };
}

/** One fully dissected example sentence — the unit the whole corpus is built on. A sentence lives here ONCE and everything else references it by id. */
export interface Sentence {
  clause_structure: string | null;
  grammar: string[];
  jp: string;
  kana: string;
  level: Level;
  new_items: unknown[];
  particles: {
      explanation?: LocaleText;
      function?: LocaleText | null;
      function_type?: "adverbial" | "binding" | "case" | "conjunctive" | "nominalizer" | "parallel" | "sentence-final";
      particle?: string;
    }[];
  pattern: {
      chunk?: string;
      particle?: string;
      role?: string;
    }[] | null;
  provenance: {
    ai_generated: boolean;
    jp_source: string;
    locale: string;
    needs_review: boolean;
    pt_source: "ai" | "human" | "tatoeba";
    pt_validated_against: "both" | "dict" | "en" | "none";
    tier: string;
    translation_confidence: number;
  };
  romaji: string;
  slug: StableId;
  structure_explanation: LocaleText;
  tags: string[];
  tokens: {
      conjugation_note?: LocaleText | null;
      gloss?: LocaleText | null;
      inflection?: "attributive" | "conditional" | "continuative" | "imperative" | "irrealis" | "ku-form" | "stem" | "terminal" | "volitional" | null;
      inflection_type?: string | null;
      lemma?: string;
      pos?: "adnominal" | "adverb" | "auxiliary" | "conjunction" | "filler" | "i-adjective" | "interjection" | "na-adjective" | "noun" | "numeral" | "particle" | "prefix" | "pronoun" | "punctuation" | "suffix" | "symbol" | "verb" | "whitespace" | null;
      pos_coarse?: string;
      pos_fine?: string;
      position?: number;
      reading?: string;
      role?: LocaleText | null;
      romaji?: string | null;
      split_mode?: "A" | "B" | "C";
      surface?: string;
      vocab?: string | null;
      vocab_id?: number | null;
    }[];
  translation: LocaleText;
  translation_literal: LocaleText;
}

/** The root of the situation-ordered path (Fala Primeiro): its stages and totals. */
export interface SpeakPath {
  description: LocaleText;
  id: StableId;
  layer: Layer;
  needs_review: boolean;
  ordering: string;
  schema_version: string;
  shortfall: unknown[];
  spec: string;
  stages: {
      approx_band?: string;
      order?: number;
      slug?: StableId;
      title?: LocaleText;
      unit_count?: number;
      unit_ids?: string[];
    }[];
  title: LocaleText;
  totals: {
    checkpoint_items: number;
    drills: number;
    fluency: number;
    patterns_chunked: number;
    patterns_kept: number;
    phrases: number;
    production: number;
    real_phrases: number;
    stages: number;
    units: number;
    vocab_introduced: number;
  };
}

/** One unit of the speaking path: phrases, drills and a checkpoint for a single situation. */
export interface SpeakUnit {
  audio: string;
  checkpoint: {
      distractors?: string[];
      id?: StableId;
      type?: "context_fill" | "grammar_form" | "kanji_reading" | "orthography" | "paraphrase" | "reading_comp" | "sentence_order" | "text_grammar" | "usage";
      via?: "new-word" | "phrase" | "review";
    }[];
  chunk_phrases: StableId[];
  cumulative_known_vocab: number;
  drills: {
      examples?: string[];
      pattern?: string;
      strand?: "fluency" | "language-focused" | "meaning-input" | "meaning-output";
    }[];
  fluency: {
    items?: string[];
    kind?: "recap" | "situation";
    prompt_pt?: string;
    seconds_target?: number;
    strand?: "fluency" | "language-focused" | "meaning-input" | "meaning-output";
    zero_new_tokens?: boolean;
  };
  id: StableId;
  kanji_recognition: string[];
  layer: Layer;
  needs_review: boolean;
  order: number;
  patterns: string[];
  patterns_chunked: string[];
  production: {
      accepted_variants?: string[];
      answer_key?: string;
      prompt_pt?: string;
      sentence?: string;
      strand?: "fluency" | "language-focused" | "meaning-input" | "meaning-output";
    }[];
  real_phrases: number;
  say_now: string[];
  schema_version: string;
  shadowing: string[];
  stage: StableId;
  strand_counts: {
    fluency: number;
    "language-focused": number;
    "meaning-input": number;
    "meaning-output": number;
  };
  strands: {
    fluency: number;
    "language-focused": number;
    "meaning-input": number;
    "meaning-output": number;
  };
  title: LocaleText;
  untranslated: unknown[];
  words: string[];
}

/** Stroke data for one kana character, including the shadow guides used when tracing. */
export interface StrokeKana {
  char: string;
  kind: "hiragana" | "katakana";
  license: string;
  shadows: unknown[][];
  "shadows[]"?: Record<string, unknown>;
  source: string;
  strokes: string[];
  viewbox: string;
}

/** Raw stroke path geometry for one kanji. */
export interface StrokeLines {
  character: string;
  license: string;
  source: string;
  strokes: string[];
}

/** Ordered stroke steps for one kanji, for animating how it is written. */
export interface StrokeOrder {
  character: string;
  license: string;
  source: string;
  steps: string[];
  total_strokes: number;
  transform: string;
  viewbox: string;
}

/** A block of lessons that closes one theme, and the items it unlocks. */
export interface Topic {
  id: StableId;
  lessons: {
      description?: LocaleText;
      id?: StableId;
      needs?: unknown[];
      order?: number;
      path?: string;
      title?: LocaleText;
      unlocks?: {
          ref?: string;
          type?: "conjugation-form" | "feature" | "grammar" | "kana-family" | "kanji" | "kanji-family" | "phrase" | "srs-deck" | "vocab";
        }[];
    }[];
  level: Level;
  objectives: LocaleText[];
  order: number;
  theme: string;
  title: LocaleText;
}

/** One dictionary word, keyed by its JMdict entry. Carries senses, pitch, inflection class and the consensus level. */
export interface Vocab {
  adj_class: "i_adj" | "na_adj" | null;
  common: boolean;
  families: string[];
  forms: {
      form?: string;
      is_common?: boolean;
      is_kana?: boolean;
      is_primary?: boolean;
    }[];
  headword: string;
  id: number;
  jmdict_ref: string;
  kana: string;
  kanji: string[];
  level: Level;
  level_agreement: string | null;
  level_confidence: number | null;
  level_sources: Record<string, unknown> | null;
  lexeme_type: "aux" | "counter" | "expression" | "prefix" | "suffix" | "suru_verb" | "word";
  notes: LocaleText | null;
  pitch: {
      accent_positions?: number[];
      reading?: string;
    }[];
  register: "archaic" | "colloquial" | "familiar" | "honorific" | "humble" | "polite" | "slang" | "vulgar"[] | null;
  romaji: string;
  senses: {
      field?: unknown[];
      gloss?: LocaleTextList;
      misc?: string[];
      order?: number;
      pos?: string[];
      register?: "archaic" | "colloquial" | "familiar" | "honorific" | "humble" | "polite" | "slang" | "vulgar"[] | null;
    }[];
  slug: StableId;
  verb_class: "godan" | "ichidan" | "kuru_irregular" | "suru_irregular" | null;
}
