// GENERATED by scripts/contracts/build_manifest.py from contracts/*.schema.json — do not edit.
//
// The corpus is private paid content. These are TYPES only; importing them pulls in no data, and the
// JSON they describe must never reach a client bundle (see prototype/README.md on the SSR-only rule).

/** Learner-facing prose, per locale. pt-BR is always present; `en` is the Layer-A source when there was one. */
export interface LocaleText { "pt-BR": string; en?: string; [locale: string]: string | undefined }

/** Like LocaleText for fields that are plural in every locale (a kanji's meanings, a sense's glosses). */
export interface LocaleTextList { "pt-BR": string[]; en?: string[]; [locale: string]: string[] | undefined }

/** A prefixed stable id: "kanji:食", "vocab:1580640", "les:n5-saudacoes-01". */
export type StableId = string;

export type Level = "pre-n5" | "n5" | "n4" | "n3" | "n2" | "n1";

/** A = authoritative (zero AI) · B = derived and machine-verified · C = pedagogy, needs a teacher. */
export type Layer = "A" | "B" | "C";

/** Something a learner can DO once a set of lessons is complete. The bridge between the syllabus and the exam. */
export interface Capability {
  grammar_keys: string[];
  id: StableId;
  level: Level;
  name: LocaleText;
}

/** Which capabilities each lesson contributes to. A keyed collection rather than a record list: the lesson id IS the key, so there is no id field inside the value. Hand-authored — a map's contract is about its key space and value shape, which the record-shape generator has no idiom for. */
export type CapabilityLessonMap = Record<string, unknown>;

/** The full inflection table for one verb or adjective, keyed by the vocab entry it belongs to. */
export interface Conjugation {
  class: "godan" | "i_adj" | "ichidan" | "kuru_irregular" | "na_adj" | "suru_irregular";
  conjugations: {
      form?: "adverbial" | "attributive" | "causative" | "causative_passive" | "conditional_ba" | "conditional_tara" | "dictionary" | "imperative" | "masu" | "masu_negative" | "masu_past" | "masu_past_negative" | "negative" | "negative_te" | "passive" | "past" | "past_negative" | "polite" | "polite_negative" | "polite_past" | "potential" | "te" | "volitional" | "volitional_polite";
      kana?: string;
      romaji?: string;
      surface?: string;
    }[];
  headword: string;
  kana: string;
  kind: "adjective" | "verb";
  level: Level;
  slug: StableId;
  vocab_id: number;
}

/** A course root for one level: its ordered topics and the overview shown before the first lesson. */
export interface Course {
  id: StableId;
  level: Level;
  order: number;
  overview: LocaleText;
  title: LocaleText;
  topics: {
      id?: StableId;
      lesson_count?: number;
      order?: number;
      path?: string;
      theme?: string;
      title?: LocaleText;
      unlocks_summary?: {
        grammar?: number;
        kanji?: number;
        vocab?: number;
      };
    }[];
}

/** The index an API reads first: every course, where its root lives, and how much is in it. */
export interface CourseManifest {
  courses: {
      id?: StableId;
      lesson_count?: number;
      level?: Level;
      order?: number;
      path?: "n3/course.json" | "n4/course.json" | "n5/course.json" | "pre-n5/course.json";
      title?: LocaleText;
      topic_count?: number;
    }[];
  enums_ref: "design/unlock_enums.json";
  generated: "2026-08-26";
  schema_version: "1.0";
}

/** One JLPT-style practice question, drawn from the corpus so every item is also findable in a lesson. */
export interface ExamItem {
  ai_generated?: boolean;
  answer?: string;
  audio?: "pending";
  correct?: string;
  distractors?: string[];
  grammar?: string;
  id: StableId;
  layer?: Layer;
  level: Level;
  needs_review?: boolean;
  pieces?: string[];
  question?: string;
  reading?: string;
  script?: {
      speaker?: "F1" | "F2" | "M1" | "M2" | "N";
      text?: string;
    }[];
  sentence?: string;
  source?: string;
  stem?: string;
  target?: string;
  vocab_id?: number;
  wrong?: string[];
}

/** One generated conjugation drill: a prompt form, the correct inflection, and three distractors. */
export interface ExerciseConjugation {
  class: "godan" | "i_adj" | "ichidan" | "kuru_irregular" | "na_adj" | "suru_irregular";
  correct: string;
  distractors: string[];
  example: string | null;
  form: "adverbial" | "attributive" | "causative" | "causative_passive" | "conditional_ba" | "conditional_tara" | "imperative" | "masu" | "masu_negative" | "masu_past" | "masu_past_negative" | "negative" | "negative_te" | "passive" | "past" | "past_negative" | "polite" | "polite_negative" | "polite_past" | "potential" | "te" | "volitional" | "volitional_polite";
  form_label: LocaleText;
  headword: string;
  id: StableId;
  kana: string;
  kind: "adjective" | "verb";
  layer: Layer;
  level: Level;
  needs_review: boolean;
  prompt: string;
  romaji: string;
  slug: StableId;
  source: string;
  vocab_id: number;
}

/** One generated particle-role drill, derived mechanically from a sentence's own particles. */
export interface ExerciseRole {
  correct: string;
  distractors: string[];
  id: StableId;
  jp: string;
  layer: Layer;
  level: Level;
  needs_review: boolean;
  particle: "\u304b\u3089" | "\u304c" | "\u306e" | "\u306f" | "\u3078" | "\u3092" | null;
  prompt: LocaleText;
  role: "direction" | "from" | "modifier" | "object" | "predicate" | "subject" | "topic";
  sentence: string;
  source: string;
}

/** A group of items that behave alike (a conjugation class, a particle set, a semantic field), with the rule that governs the group. */
export interface Family {
  description: null;
  governing_rule: LocaleText | null;
  id: number;
  importance_rank: number;
  label: LocaleText;
  members: {
      id?: number;
      intra_order?: number;
      is_core?: boolean;
      member_type?: "grammar" | "kanji" | "vocab";
      note?: null;
      ref?: string;
    }[];
  slug: StableId;
  spans_levels: "n4" | "n5"[];
  type: "conjugation_class" | "contrast_pair" | "function_set" | "kanji_component" | "particle_set" | "semantic_field" | "word_family";
}

/** One grammar point: its forms, how it is formed, what it contrasts with, and the pedagogy around it. */
export interface Grammar {
  caution: "rough" | "sensitive" | null;
  explanation: LocaleText;
  formation: LocaleText;
  formation_steps: {
    variants?: {
        base?: "clause" | "i-adjective" | "na-adjective" | "noun" | "verb";
        example?: string;
        steps?: unknown[];
      }[];
  };
  forms: {
      form?: string;
      meaning?: LocaleText | null;
    }[];
  id: number;
  key: string;
  label: LocaleText;
  level: Level;
  level_agreement: string | null;
  level_confidence: number | null;
  level_sources: {
    bunpro?: "n4" | "n5";
    hanabira?: "n3";
    jlptsensei?: "n4" | "n5";
    note?: "course anchor for the \u3066-form hub";
    tanos?: "n4" | "n5";
  };
  needs_review: boolean;
  nuance: LocaleText;
  nuance_tags: "cause" | "change-of-state" | "comparison" | "completion" | "concession" | "condition" | "conjecture" | "continuation" | "desire" | "emphasis" | "experience" | "hearsay" | "honorific" | "humility" | "intention" | "obligation" | "permission" | "politeness" | "prohibition" | "request" | "softening"[];
  refs: {
    also_known_as?: string[];
    label_en?: string;
    level_sources?: {
      bunpro?: "n4" | "n5";
      jlptsensei?: "n4" | "n5";
      tanos?: "n4" | "n5";
    };
  };
  register: "casual" | "colloquial" | "feminine" | "formal" | "honorific" | "humble" | "literary" | "masculine" | "neutral" | "plain" | "polite" | "written"[];
  related: "de" | "ga" | "ni" | "wa-topic-marker"[];
  slug: StableId;
  steps_unavailable: string | null;
  structure_pattern: string;
  usage_contexts: "academic" | "announcement" | "business" | "casual-friends" | "formal-email" | "literary" | "spoken" | "written"[];
}

/** One hiragana or katakana character and the family it belongs to. */
export interface Kana {
  char: string;
  family: string;
  family_label: LocaleText;
  id: StableId;
  romaji: string;
  type: "base" | "dakuten" | "handakuten" | "long-vowel" | "sokuon" | "yoon";
}

/** The kana chart as ordered groups. Keyed by script, so unlike the capability map its keys are a fixed enum rather than stable IDs — which is why the two map-packed files cannot share one generated shape. */
export type KanaFamily = Record<string, unknown>;

/** One kanji character: readings, meanings, radical decomposition and the level it is taught at. Layer A apart from the pt-BR meanings. */
export interface Kanji {
  character: string;
  components: string[];
  example_sentences: string[];
  example_words: {
      gloss?: LocaleTextList;
      headword?: string;
      kana?: string;
      slug?: StableId;
      vocab_id?: number;
    }[];
  freq_rank: number | null;
  grade: number;
  id: number;
  irregular_note: LocaleText | null;
  kangxi_radical: number;
  kanjivg_ref: string;
  level: Level;
  level_agreement: string | null;
  level_confidence: number | null;
  level_sources: {
    anchor?: "jlpt_anchor:n4" | "jlpt_anchor:n5" | "jlpt_anchor:not-in-n5n4";
    anchori?: "n1" | "n2" | "n4" | "n5";
    bluskyo?: "n1" | "n2" | "n3" | "n4" | "n5";
    davidluzgouveia?: "n1" | "n2" | "n3" | "n4" | "n5";
    kanjiapi?: "n1" | "n2" | "n3" | "n4" | "n5";
    lists?: "author-added: usado por vocabul\u00e1rio N4; fora das listas de consenso"[];
  };
  meanings: LocaleTextList;
  notes: null;
  radical_char: string;
  readings: {
      common?: boolean;
      example_vocab_ids?: number[] | null;
      introduced_at_level?: "n4" | "n5" | null;
      note?: LocaleText | null;
      okurigana?: string | null;
      reading?: string;
      type?: "kun" | "nanori" | "on";
    }[];
  slug: StableId;
  strokes: number;
  unicode: string;
}

/** The leaf unit a learner sits down to. Holds objectives, explanation, exercises and the items it introduces — all corpus content by REFERENCE, never embedded. */
export interface Lesson {
  body: string;
  cumulative_known_set: {
    "conjugation-form": unknown[];
    grammar: string[];
    "kana-family": string[];
    kanji: string[];
    phrase: unknown[];
    vocab: string[];
  };
  description: LocaleText;
  exercises: {
      answer?: {
        accept?: unknown[];
        choices?: unknown[];
        correct?: string;
        full?: string;
        order?: unknown[];
        pairs?: unknown[];
        sentence_refs?: unknown[];
        text?: string;
      };
      explanation?: LocaleText;
      id?: StableId;
      prompt?: LocaleText;
      sentence_refs?: string[];
      type?: "cloze" | "matching" | "particle_choice" | "production" | "recognition" | "sentence_build";
    }[];
  feature_unlocks: "feat:conjugation-drill" | "feat:jlpt-sim-n4" | "feat:jlpt-sim-n5" | "feat:srs-reviews"[];
  id: StableId;
  level: Level;
  needs: unknown[];
  needs_review: boolean;
  objectives: LocaleText[];
  order: number;
  schema_version: "1.0";
  sentence_refs: string[];
  srs: {
    introduces_cards: {
        card_types?: unknown[];
        deck?: "deck:grammar-n4" | "deck:grammar-n5" | "deck:kana-hiragana" | "deck:kana-katakana" | "deck:kanji-n4" | "deck:kanji-n5" | "deck:vocab-n4" | "deck:vocab-n5";
        item?: string;
      }[];
  };
  title: LocaleText;
  topic: string;
  unlocks: {
      ref?: string;
      type?: "feature" | "grammar" | "kana-family" | "kanji" | "vocab";
    }[];
}

/** A short reading passage gated to a lesson, with its tokens and translation. */
export interface Reading {
  ai_generated: boolean;
  gated_to_lesson: string;
  jp: string;
  layer: Layer;
  length_band: "long" | "paragraph" | "short";
  level: Level;
  needs_review: boolean;
  slug: StableId;
  source_slugs: string[];
  title: LocaleText;
  tokens: {
      pos?: "adnominal" | "adverb" | "auxiliary" | "conjunction" | "i-adjective" | "interjection" | "na-adjective" | "noun" | "particle" | "prefix" | "pronoun" | "punctuation" | "suffix" | "verb" | "whitespace";
      r?: string;
      ro?: string;
      s?: string;
    }[];
  translation: LocaleText;
  uses: {
    kanji: string[];
    vocab: string[];
  };
}

/** One fully dissected example sentence — the unit the whole corpus is built on. A sentence lives here ONCE and everything else references it by id. */
export interface Sentence {
  clause_structure: "cause" | "conditional" | "coordinate" | "fragment" | "imperative" | "question" | "quote" | "relative-clause" | "simple" | "subordinate-time" | "topic-comment" | null;
  grammar: string[];
  jp: string;
  kana: string;
  level: Level;
  new_items: unknown[];
  particles: {
      explanation?: LocaleText;
      function?: LocaleText | null;
      function_type?: "adverbial" | "binding" | "case" | "conjunctive" | "nominalizer" | "sentence-final";
      particle?: string;
    }[];
  pattern: {
      chunk?: string;
      particle?: string;
      role?: "also" | "de-clause" | "de-phrase" | "direction" | "from" | "ga-clause" | "kara-clause" | "modifier" | "ni-phrase" | "nominalizer" | "object" | "phrase" | "predicate" | "sentence-final" | "subject" | "te-kara" | "than" | "to-clause" | "to-phrase" | "topic" | "until";
    }[] | null;
  provenance: {
    ai_generated: boolean;
    jp_source: string;
    locale: "pt-BR";
    needs_review: boolean;
    pt_source: "ai";
    pt_validated_against: "dict" | "en";
    tier: "full";
    translation_confidence: number;
  };
  romaji: string;
  slug: StableId;
  structure_explanation: LocaleText;
  tags: string[];
  tokens: {
      conjugation_note?: LocaleText | null;
      gloss?: LocaleText | null;
      inflection?: "attributive" | "conditional" | "continuative" | "imperative" | "irrealis" | "stem" | "terminal" | "volitional" | null;
      inflection_type?: string | null;
      lemma?: string;
      pos?: "adnominal" | "adverb" | "auxiliary" | "conjunction" | "i-adjective" | "interjection" | "na-adjective" | "noun" | "particle" | "prefix" | "pronoun" | "punctuation" | "suffix" | "verb" | "whitespace" | null;
      pos_coarse?: "\u4ee3\u540d\u8a5e" | "\u526f\u8a5e" | "\u52a9\u52d5\u8a5e" | "\u52a9\u8a5e" | "\u52d5\u8a5e" | "\u540d\u8a5e" | "\u5f62\u5bb9\u8a5e" | "\u5f62\u72b6\u8a5e" | "\u611f\u52d5\u8a5e" | "\u63a5\u5c3e\u8f9e" | "\u63a5\u7d9a\u8a5e" | "\u63a5\u982d\u8f9e" | "\u7a7a\u767d" | "\u88dc\u52a9\u8a18\u53f7" | "\u9023\u4f53\u8a5e";
      pos_fine?: "*" | "\u30bf\u30ea" | "\u30d5\u30a3\u30e9\u30fc" | "\u4e00\u822c" | "\u4fc2\u52a9\u8a5e" | "\u526f\u52a9\u8a5e" | "\u52a9\u52d5\u8a5e\u8a9e\u5e79" | "\u52d5\u8a5e\u7684" | "\u53e5\u70b9" | "\u540d\u8a5e\u7684" | "\u56fa\u6709\u540d\u8a5e" | "\u5f62\u5bb9\u8a5e\u7684" | "\u5f62\u72b6\u8a5e\u7684" | "\u62ec\u5f27\u9589" | "\u62ec\u5f27\u958b" | "\u63a5\u7d9a\u52a9\u8a5e" | "\u6570\u8a5e" | "\u666e\u901a\u540d\u8a5e" | "\u683c\u52a9\u8a5e" | "\u6e96\u4f53\u52a9\u8a5e" | "\u7d42\u52a9\u8a5e" | "\u8aad\u70b9" | "\u975e\u81ea\u7acb\u53ef\u80fd";
      position?: number;
      reading?: string;
      role?: LocaleText | null;
      romaji?: string | null;
      split_mode?: "A" | "C";
      surface?: string;
      vocab_id?: number | null;
    }[];
  translation: LocaleText;
  translation_literal: LocaleText;
}

/** The root of the situation-ordered path (Fala Primeiro): its stages and totals. */
export interface SpeakPath {
  description: LocaleText;
  id: StableId;
  layer: Layer;
  needs_review: boolean;
  ordering: "survival scenario (primary) + vocab.freq_rank (secondary)";
  schema_version: "1.0";
  shortfall: unknown[];
  spec: "design/speaking_path.md";
  stages: {
      approx_band?: "n3" | "n4" | "n4/n3" | "n5" | "n5/n4" | "pre-n5" | "pre-n5/n5";
      order?: number;
      slug?: StableId;
      title?: LocaleText;
      unit_count?: number;
      unit_ids?: string[];
    }[];
  title: LocaleText;
  totals: {
    checkpoint_items: number;
    drills: number;
    fluency: number;
    patterns_chunked: number;
    patterns_kept: number;
    phrases: number;
    production: number;
    real_phrases: number;
    stages: number;
    units: number;
    vocab_introduced: number;
  };
}

/** One unit of the speaking path: phrases, drills and a checkpoint for a single situation. */
export interface SpeakUnit {
  audio: "pending";
  checkpoint: {
      distractors?: string[];
      id?: StableId;
      type?: "context_fill" | "kanji_reading" | "paraphrase" | "sentence_order";
      via?: "new-word" | "phrase" | "review";
    }[];
  chunk_phrases: "sent:tatoeba-13174949" | "sent:tatoeba-1531875" | "sent:tatoeba-1532832" | "sent:tatoeba-1576172" | "sent:tatoeba-1598216" | "sent:tatoeba-335372" | "sent:tatoeba-3480287" | "sent:tatoeba-3553332" | "sent:tatoeba-373351" | "sent:tatoeba-408301" | "sent:tatoeba-426889" | "sent:tatoeba-4854" | "sent:tatoeba-4971" | "sent:tatoeba-640569" | "sent:tatoeba-8467948" | "sent:tatoeba-9559301"[];
  cumulative_known_vocab: number;
  drills: {
      examples?: string[];
      pattern?: string;
      strand?: "language-focused";
    }[];
  fluency: {
    items?: string[];
    prompt_pt?: "Algu\u00e9m perguntou como foi seu fim de semana. Conte, no passado." | "Algu\u00e9m puxou assunto com voc\u00ea. Diga quem voc\u00ea \u00e9, de onde vem e do que gosta." | "Perguntaram sua opini\u00e3o. Diga o que voc\u00ea acha e por qu\u00ea." | "Um amigo quer marcar alguma coisa. Combine dia e hor\u00e1rio." | "Voc\u00ea acabou de desembarcar. Cumprimente, agrade\u00e7a e pe\u00e7a licen\u00e7a \u2014 em voz alta, sem ler." | "Voc\u00ea chegou no hotel. Fa\u00e7a o check-in e resolva um problema no quarto." | "Voc\u00ea est\u00e1 numa conversa solta. Reaja, comente e conte o que ouviu de outra pessoa." | "Voc\u00ea est\u00e1 numa loja com uma coisa na m\u00e3o. Pergunte o pre\u00e7o e feche a compra." | "Voc\u00ea n\u00e3o est\u00e1 bem. Explique o que est\u00e1 sentindo e pe\u00e7a ajuda." | "Voc\u00ea precisa pedir um favor a algu\u00e9m mais velho. Pe\u00e7a com jeito." | "Voc\u00ea se perdeu perto da esta\u00e7\u00e3o. Pergunte o caminho e confirme se entendeu." | "Voc\u00ea sentou num restaurante. Pe\u00e7a o que quer comer e beber, e diga se est\u00e1 bom.";
    seconds_target?: number;
    strand?: "fluency";
    zero_new_tokens?: boolean;
  };
  id: StableId;
  kanji_recognition: string[];
  layer: Layer;
  needs_review: boolean;
  order: number;
  patterns: string[];
  patterns_chunked: string[];
  production: {
      accepted_variants?: string[];
      answer_key?: string;
      prompt_pt?: string;
      sentence?: string;
      strand?: "meaning-output";
    }[];
  real_phrases: number;
  say_now: string[];
  schema_version: "1.0";
  shadowing: string[];
  stage: "speak:about_you" | "speak:arrival" | "speak:eating" | "speak:getting_around" | "speak:health" | "speak:lodging" | "speak:opinions" | "speak:past_stories" | "speak:politeness" | "speak:real_talk" | "speak:shopping" | "speak:time_plans";
  strand_counts: {
    fluency: number;
    "language-focused": number;
    "meaning-input": number;
    "meaning-output": number;
  };
  strands: {
    fluency: number;
    "language-focused": number;
    "meaning-input": number;
    "meaning-output": number;
  };
  title: LocaleText;
  untranslated: unknown[];
  words: string[];
}

/** Stroke data for one kana character, including the shadow guides used when tracing. */
export interface StrokeKana {
  char: string;
  kind: "hiragana" | "katakana";
  license: "OFL-1.1+MIT";
  shadows: unknown[][];
  "shadows[]"?: Record<string, unknown>;
  source: string;
  strokes: string[];
  viewbox: "0 0 1024 1024";
}

/** Raw stroke path geometry for one kanji. */
export interface StrokeLines {
  character: string;
  license: "GlyphWiki-free";
  source: string;
  strokes: string[];
}

/** Ordered stroke steps for one kanji, for animating how it is written. */
export interface StrokeOrder {
  character: string;
  license: "CC-BY-4.0";
  source: string;
  steps: string[];
  total_strokes: number;
  transform: "translate(0.000000,248.000000) scale(0.100000,-0.100000)";
  viewbox: "0 0 248.000000 248.000000";
}

/** A block of lessons that closes one theme, and the items it unlocks. */
export interface Topic {
  id: StableId;
  lessons: {
      description?: LocaleText;
      id?: StableId;
      needs?: unknown[];
      order?: number;
      path?: string;
      title?: LocaleText;
      unlocks?: {
          ref?: string;
          type?: "feature" | "grammar" | "kana-family" | "kanji" | "vocab";
        }[];
    }[];
  level: Level;
  objectives: LocaleText[];
  order: number;
  theme: string;
  title: LocaleText;
}

/** One dictionary word, keyed by its JMdict entry. Carries senses, pitch, inflection class and the consensus level. */
export interface Vocab {
  adj_class: "i_adj" | "na_adj" | null;
  common: boolean;
  forms: {
      form?: string;
      is_common?: boolean;
      is_kana?: boolean;
      is_primary?: boolean;
    }[];
  headword: string;
  id: number;
  jmdict_ref: string;
  kana: string;
  kanji: string[];
  level: Level;
  level_agreement: string | null;
  level_confidence: number | null;
  level_sources: {
    bluskyo?: "n3" | "n4" | "n5";
    correction?: "2026-07-09 kana-collision fix: bluskyo/jlptvocabapi \u305b\u3063\u3051\u3093 n5 rows mean \u77f3\u9e78 (soap, vocab:1382590); \u63a5\u898b is unlisted in every ingested JLPT list -> conservative n1 (advanced formal/legal term)";
    elzup?: "n4" | "n5";
    "jlpt-lists"?: "n1" | "n2";
    jlptvocabapi?: "n4" | "n5";
    openanki?: "n4" | "n5";
  };
  lexeme_type: "counter" | "suru_verb" | "word";
  notes: LocaleText | null;
  pitch: {
      accent_positions?: number[];
      reading?: string;
    }[];
  register: "humble"[] | null;
  romaji: string;
  senses: {
      field?: unknown[];
      gloss?: LocaleTextList;
      misc?: "hum"[];
      order?: number;
      pos?: string[];
      register?: "humble"[] | null;
    }[];
  slug: StableId;
  verb_class: "godan" | "ichidan" | "kuru_irregular" | "suru_irregular" | null;
}
