#!/usr/bin/env python3
"""Gate: prototype/app/data/*.json is the CURRENT projection of corpus/ + course/.

WHY THIS EXISTS (review finding F11)
------------------------------------
The product does not ship `corpus/` and `course/`; it ships the sixteen consolidated JSON files
under `prototype/app/data/`, generated by `prototype/scripts/sync-data.mjs` and COMMITTED. A grep
of scripts/validate/*.py for "prototype" used to return exactly one hit — a comment. So the two
derived copies the app actually reads were validated by nothing: edit a lesson body, forget to run
`npm run sync-data`, and every gate in the suite still passes while the app serves last month's
text. prototype/README.md states the rule ("re-generate it whenever the corpus changes") and left a
human to remember it.

HOW IT CHECKS
-------------
Rather than sniff record shapes and keep a hand-written list of "fields the sync script drops"
(which rots the moment sync-data.mjs changes), this validator RE-DERIVES all sixteen outputs in
Python — a line-by-line port of sync-data.mjs's projection, including its deliberate slimming
(`slimSentence`, `slimToken`, `slimParticle`, `slimReading`), its `indexBySlugIdent` vocabulary
keying, and its file-name regexes — and deep-compares the result against the committed files. An
UNdocumented omission therefore fails, and so does an extra field, a stale record and a stale id
set. Any change to sync-data.mjs must be mirrored in PROJECTION below (the port is annotated with
the .mjs line it mirrors), which is the point: the projection is a contract, not a side effect.

Reads the exported JSON only — never db/corpus.sqlite.

Usage: validate_prototype_sync.py [--root PATH] [--list N]
Exit 1 on any id-set or field difference; the fix is `cd prototype && npm run sync-data`.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
REPO_ROOT = Path(__file__).resolve().parents[2]

# The sixteen files sync-data.mjs writes (mjs lines 216-231). A file missing here would be an
# unvalidated output, so the set itself is compared against what app/data actually holds.
OUTPUTS = ("courses.json", "topics.json", "lessons.json", "kanji.json", "vocab.json",
           "grammar.json", "sentences.json", "kana.json", "strokes.json", "strokeLines.json",
           "kanaStrokes.json", "readings.json", "examBanks.json", "conjugationBank.json",
           "roleBank.json", "speakPath.json")


# --------------------------------------------------------------------------- mjs helper ports
def _read_json(p: Path) -> Any:
    return json.loads(p.read_text(encoding="utf-8"))


def _read_corpus_list(corpus: Path, sub: str) -> list:
    """Port of readCorpusList (mjs 27-39): merge every *.json in corpus/<sub> into one array.

    Sorted rather than readdir-order: the only behavioural difference is which file wins a
    duplicate key, and the corpus has none (levels are disjoint). Sorted is reproducible.
    """
    d = corpus / sub
    if not d.is_dir():
        return []
    out: list = []
    for f in sorted(d.glob("*.json")):
        data = _read_json(f)
        if isinstance(data, list):
            out.extend(data)
        elif isinstance(data, dict) and isinstance(data.get(sub), list):
            out.extend(data[sub])
    return out


def _index_by(arr: list, key: str) -> dict:
    """Port of indexBy (mjs 41-45): skips records whose key is null/absent; last one wins."""
    o: dict = {}
    for it in arr:
        if isinstance(it, dict) and it.get(key) is not None:
            o[it[key]] = it
    return o


def _index_by_slug_ident(arr: list) -> dict:
    """Port of indexBySlugIdent (mjs 54-63): "vocab:1580640" -> key "1580640".

    Vocabulary cannot be keyed by headword — 93 headwords name 193 records.
    """
    o: dict = {}
    for it in arr:
        slug = it.get("slug") if isinstance(it, dict) else None
        if not isinstance(slug, str):
            continue
        i = slug.find(":")
        o[slug if i == -1 else slug[i + 1:]] = it
    return o


def _pick(src: dict, keys: tuple[str, ...]) -> dict:
    """JSON.stringify drops keys whose value is `undefined`; an absent source key must stay absent."""
    return {k: src[k] for k in keys if k in src}


def _pt(v: Any) -> Any:
    """Port of pt() (mjs 132): locale-object -> pt-BR, else en, else ""."""
    if isinstance(v, dict):
        r = v.get("pt-BR")
        if r is None:
            r = v.get("en")
        return "" if r is None else r
    if isinstance(v, list):
        return ""          # a non-locale object has neither key -> "" in JS too
    return "" if v is None else v


_ROMAJI_PUNCT = re.compile(r"\s+([?!,.;:、。？！])")


def _spaced_romaji(s: dict) -> str:
    """Port of spacedRomaji (mjs 124-128): rebuild space-separated romaji from the token romaji."""
    toks = [t.get("romaji") for t in (s.get("tokens") or []) if isinstance(t, dict) and t.get("romaji")]
    if not toks:
        return s.get("romaji") or ""
    return _ROMAJI_PUNCT.sub(r"\1", " ".join(toks)).strip()


def _slim_token(t: dict) -> dict:
    """Port of slimToken (mjs 133)."""
    o = {}
    for src, dst in (("surface", "s"), ("reading", "r"), ("romaji", "ro"), ("pos", "pos")):
        if src in t:
            o[dst] = t[src]
    o["gloss"] = _pt(t.get("gloss"))
    o["role"] = _pt(t.get("role"))
    return o


def _slim_particle(p: dict) -> dict:
    """Port of slimParticle (mjs 134)."""
    o = {}
    for src, dst in (("particle", "p"), ("function_type", "ft")):
        if src in p:
            o[dst] = p[src]
    o["fn"] = _pt(p.get("function"))
    o["ex"] = _pt(p.get("explanation"))
    return o


def _slim_sentence(s: dict) -> dict:
    """Port of slimSentence (mjs 135-141): display fields + grammar tags + full token/particle
    dissection, with the heavy analysis dropped. Server-only in the app."""
    o = _pick(s, ("slug", "jp", "kana"))
    o["romaji"] = _spaced_romaji(s)
    o.update(_pick(s, ("translation", "translation_literal", "structure_explanation", "level")))
    o["grammar"] = s.get("grammar") or []
    o["tokens"] = [_slim_token(t) for t in (s.get("tokens") or [])]
    o["particles"] = [_slim_particle(p) for p in (s.get("particles") or [])]
    return o


def _slim_reading(r: dict) -> dict:
    """Port of slimReading (mjs 146-150)."""
    o = _pick(r, ("slug", "jp", "title", "translation"))
    o["tokens"] = [_pick(t, ("s", "r", "ro", "pos")) for t in (r.get("tokens") or [])]
    o.update(_pick(r, ("length_band",)))
    o["source_slugs"] = r.get("source_slugs") or []
    return o


# --------------------------------------------------------------------------- the projection
def build_projection(root: Path) -> dict[str, Any]:
    """Re-run sync-data.mjs's projection in Python. Returns {output filename: value}."""
    course, corpus = root / "course", root / "corpus"
    proj: dict[str, Any] = {}

    # ---- courseware: manifest -> courses -> topics -> lesson leaves (mjs 72-99) ----
    manifest = _read_json(course / "manifest.json")
    courses: list = []
    topics: dict = {}
    lessons: dict = {}
    for c in manifest["courses"]:
        cdir = course / re.sub(r"/course\.json$", "", c["path"])
        cjson = _read_json(course / c["path"])
        topic_stubs = []
        for t in cjson.get("topics") or []:
            tjson = _read_json(cdir / t["path"])
            lesson_stubs = []
            for lstub in tjson.get("lessons") or []:
                leaf = _read_json(cdir / lstub["path"])
                lessons[leaf["id"]] = leaf
                lesson_stubs.append({"id": leaf["id"], "order": leaf.get("order"),
                                     **_pick(lstub, ("title", "description", "needs", "unlocks"))})
            topics[t["id"]] = {"id": t["id"],
                               **_pick(tjson, ("level", "order", "title", "theme", "objectives")),
                               **_pick(t, ("unlocks_summary",)), "lessons": lesson_stubs}
            topic_stubs.append({"id": t["id"],
                                **_pick(t, ("order", "title", "theme", "lesson_count",
                                            "unlocks_summary")),
                                "lessons": [x["id"] for x in lesson_stubs]})
        courses.append({**_pick(c, ("id", "level", "order", "title", "topic_count", "lesson_count")),
                        **_pick(cjson, ("overview",)), "topics": topic_stubs})
    proj["courses.json"] = courses
    proj["topics.json"] = topics
    proj["lessons.json"] = lessons

    # ---- corpus registries (mjs 101-117) ----
    proj["kanji.json"] = _index_by(_read_corpus_list(corpus, "kanji"), "character")
    proj["vocab.json"] = _index_by_slug_ident(_read_corpus_list(corpus, "vocab"))
    proj["grammar.json"] = _index_by(_read_corpus_list(corpus, "grammar"), "key")
    strokes_all = _read_corpus_list(corpus, "strokes")
    proj["strokes.json"] = _index_by([x for x in strokes_all
                                      if isinstance(x, dict) and isinstance(x.get("steps"), list)],
                                     "character")
    stroke_lines: dict = {}
    for it in strokes_all:
        if isinstance(it, dict) and it.get("character") and isinstance(it.get("strokes"), list):
            stroke_lines[it["character"]] = {"strokes": it["strokes"]}
    proj["strokeLines.json"] = stroke_lines
    kana_stroke_file = corpus / "strokes" / "kana.json"
    proj["kanaStrokes.json"] = (_index_by(_read_json(kana_stroke_file), "char")
                                if kana_stroke_file.exists() else {})

    # ---- sentences / readings, slimmed (mjs 118-152) ----
    proj["sentences.json"] = {s["slug"]: _slim_sentence(s)
                              for s in _read_corpus_list(corpus, "sentences")
                              if isinstance(s, dict) and s.get("slug")}
    proj["readings.json"] = {r["slug"]: _slim_reading(r)
                             for r in _read_corpus_list(corpus, "readings")
                             if isinstance(r, dict) and r.get("slug")}

    # ---- exam banks (mjs 153-166) ----
    exam: dict = {}
    eb = corpus / "exam_banks"
    if eb.is_dir():
        for f in sorted(eb.glob("*.json")):
            m = re.fullmatch(r"(n[1-5])_(.+)\.json", f.name)
            if not m:
                continue
            items = _read_json(f)
            if not isinstance(items, list) or not items:
                continue
            exam.setdefault(m.group(1), {})[m.group(2)] = items
    proj["examBanks.json"] = exam

    # ---- speaking path (mjs 168-182) ----
    speak_dir = course / "speak"
    speak: Any = None
    if (speak_dir / "course.json").exists():
        speak = _read_json(speak_dir / "course.json")
        speak["units"] = {}
        for stage in speak["stages"]:
            d = speak_dir / stage["slug"].split(":")[1]
            for f in sorted(d.glob("*.json")):
                u = _read_json(f)
                speak["units"][u["id"]] = u
    proj["speakPath.json"] = speak if speak is not None else {"stages": [], "units": {}, "totals": {}}

    # ---- conjugation / role drill banks (mjs 184-208) ----
    for out_name, sub, pattern in (("conjugationBank.json", "conjugation", r"(n[1-5])_conjugation\.json"),
                                   ("roleBank.json", "roles", r"(n[1-5])_roles\.json")):
        bank: dict = {}
        d = corpus / "exercises" / sub
        if d.is_dir():
            for f in sorted(d.glob("*.json")):
                m = re.fullmatch(pattern, f.name)
                if not m:
                    continue
                items = _read_json(f)
                if isinstance(items, list) and items:
                    bank[m.group(1)] = items
        proj[out_name] = bank

    # ---- kana families, copied verbatim (mjs 210-212) ----
    kf = corpus / "kana" / "families.json"
    proj["kana.json"] = _read_json(kf) if kf.exists() else {}
    return proj


# --------------------------------------------------------------------------- comparison
def _diff(want: Any, got: Any, path: str, out: list[str], cap: int) -> None:
    """Collect up to `cap` differences as json-path strings. `want` = re-derived, `got` = committed."""
    if len(out) >= cap:
        return
    if isinstance(want, dict) and isinstance(got, dict):
        for k in sorted(set(want) | set(got), key=str):
            if len(out) >= cap:
                return
            if k not in got:
                out.append(f"{path}.{k}: missing in app/data (stale sync)")
            elif k not in want:
                out.append(f"{path}.{k}: present in app/data but not in the corpus projection")
            else:
                _diff(want[k], got[k], f"{path}.{k}", out, cap)
        return
    if isinstance(want, list) and isinstance(got, list):
        if len(want) != len(got):
            out.append(f"{path}: length {len(got)} in app/data, {len(want)} derived")
            return
        for i, (a, b) in enumerate(zip(want, got)):
            if len(out) >= cap:
                return
            _diff(a, b, f"{path}[{i}]", out, cap)
        return
    if want != got:
        out.append(f"{path}: app/data={_short(got)} derived={_short(want)}")


def _short(v: Any) -> str:
    s = json.dumps(v, ensure_ascii=False) if not isinstance(v, str) else v
    return s if len(s) <= 70 else s[:67] + "..."


def _record_count(name: str, v: Any) -> int:
    """Records, not top-level keys — so the printed numbers are the ones F11 measured by hand
    (examBanks 6166, roleBank 5358, conjugationBank 18524, speakPath 72 units)."""
    if name == "examBanks.json":
        return sum(len(items) for by_type in v.values() for items in by_type.values())
    if name in ("conjugationBank.json", "roleBank.json"):
        return sum(len(items) for items in v.values())
    if name == "speakPath.json":
        return len(v.get("units", {}))
    return len(v) if isinstance(v, (dict, list)) else 1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(REPO_ROOT), help="tree to validate (default: repo root)")
    ap.add_argument("--list", type=int, default=15, help="max FAIL lines to print")
    args = ap.parse_args()
    root = Path(args.root).resolve()
    data = root / "prototype" / "app" / "data"
    if not data.is_dir():
        print(f"FAIL validate_prototype_sync: {data} is MISSING — a gate whose data vanished must FAIL, not certify nothing")
        return 1

    proj = build_projection(root)
    fails: list[str] = []
    committed_names = {p.name for p in data.glob("*.json")}
    for extra in sorted(committed_names - set(OUTPUTS)):
        fails.append(f"{extra}: file in app/data that sync-data.mjs does not write (unvalidated)")

    rows: list[tuple[str, int, int, int]] = []
    for name in OUTPUTS:
        want = proj[name]
        f = data / name
        if not f.exists():
            fails.append(f"{name}: missing from prototype/app/data")
            continue
        got = _read_json(f)
        d: list[str] = []
        _diff(want, got, name.removesuffix(".json"), d, 400)
        rows.append((name, _record_count(name, got), _record_count(name, want), len(d)))
        fails.extend(d)

    for r in fails[:args.list]:
        print("  FAIL", r)
    if len(fails) > args.list:
        print(f"  ... {len(fails) - args.list} more")
    print()
    for name, ngot, nwant, nd in rows:
        flag = "OK " if nd == 0 else "DIFF"
        print(f"  [{flag}] {name:<22} app/data {ngot:>6} / derived {nwant:>6}"
              + (f"  ({nd} diffs)" if nd else ""))
    print(f"\nvalidate_prototype_sync: {len(rows)} files, "
          + (f"FAIL {len(fails)} — run `cd prototype && npm run sync-data`" if fails else "ALL OK"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
