#!/usr/bin/env python3
"""The committed contracts must be exactly what the generators would produce from today's data.

WHY THIS EXISTS (findings F14 + F15, 2026-08-26 review)
-------------------------------------------------------
`contracts/` is generated by three scripts and validated by none of them:

  * F15 — scripts/contracts/build_schemas.py rewrites all 21 non-map schemas unconditionally. A
    hand-tuned enum or a tightened `required` is discarded on the next run with no marker, no diff
    and no warning, and nothing in the suite notices the loss. This validator is what turns
    hand-editing a generated schema into a build failure instead of a silent regression on the next
    regeneration. The same finding notes the side effect of the `if v['kind'] == 'map': continue`
    guard that protects the two hand-authored schemas: a NEW map-packed entity added to
    infer_shapes.py's FAMILIES list gets no schema file at all, and since both validate_contracts.py
    and build_manifest.py enumerate `contracts/*.schema.json`, the entity would be invisible to the
    gate and absent from the API catalogue with no error anywhere.
  * F14 — contracts/manifest.json and contracts/types.ts are generated and never checked.
    validate_contracts.py never opens manifest.json; if a glob stops matching, it prints
    "[OK ] <entity> 0 records" and passes. types.ts freshness is likewise unchecked, which is exactly
    the failure its own header warns about ("the prototype's own RawItem declared `ai?: number` for
    months after the field had been renamed").

So this regenerates everything into a TEMPORARY directory and diffs. It never writes into
`contracts/`: the generator modules are imported from the tree under test and their output constants
are redirected, so the working tree is byte-for-byte untouched whether the run passes or fails.

CHECKS
  1  _shapes.json is current      — re-infer from the data; byte-diff against the committed file.
  2  generated schemas are current — rebuild the 21 from the COMMITTED _shapes.json; byte-diff each.
  3  hand-authored schemas untouched — build_schemas must not emit capability_lesson_map/kana_family
                                       or any of the seven runtime contracts under contracts/user_state/,
                                       and every one of those files must exist on disk.
  3b runtime entities are unmeasurable — none of them may appear in _shapes.json. Its name there means
                                       records were committed for an entity contracted to have none,
                                       and the next regeneration would overwrite the hand-authored
                                       contract with whatever those records happen to look like.
  4  every FAMILIES entity has a schema — the map-entity blind spot F15 describes.
  5  manifest.json + types.ts are current — rebuild from the committed schemas; byte-diff. The
                                     ONLY two fields exempt are `build.date` and `build.git_head`
                                     (W06 release identity): they say WHEN and FROM WHAT the
                                     catalogue was cut, so a regeneration tomorrow or on another
                                     commit differs in them for a reason that has nothing to do
                                     with the contract. `build.entities` — one content hash per
                                     entity — is compared EXACTLY: a hash that moved means the
                                     data moved and the committed manifest is stale.
  6  manifest counts match reality — recount each entity from its declared glob + packing, and
                                     enforce a nonzero floor so a glob that stops matching fails.
                                     The `runtime` CLASS is the one exemption: null files and null
                                     records are correct there (design/user_state.md §12). It is
                                     granted on the declared class, and policed both ways — a runtime
                                     row that carries a glob FAILS even though the glob matches
                                     nothing, so a content entity whose exporter stopped cannot
                                     relabel itself `runtime` and go quiet.
  7  hand-authored schemas still describe their data — every object key in lesson_map.json and
                                     kana/families.json is a property the schema declares, so a new
                                     field in the data forces a deliberate schema edit.

Reads:  contracts/*, scripts/contracts/{infer_shapes,build_schemas,build_manifest}.py, and every glob
        those generators read (corpus/**, course/**, design/unlock_enums.json, scripts/ingest/*.py).
Writes: nothing. Usage: validate_schema_generation_is_current.py [--root PATH]
"""
from __future__ import annotations

import argparse
import contextlib
import importlib.util
import io
import json
import shutil
import sys
import tempfile
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
ROOT = Path(__file__).resolve().parents[2]
MAX_FAILS = 15
GENERATORS = ("infer_shapes", "build_schemas", "build_manifest")


class _Sink(io.StringIO):
    """The generators call sys.stdout.reconfigure() at import; StringIO has no such method."""

    def reconfigure(self, **_kw) -> None:  # noqa: D401
        return None


class _OutPath(Path):
    """An output path that survives being outside the repo. infer_shapes.py signs off with
    `print(f"-> {OUT.relative_to(ROOT)}")`; redirecting OUT to a temp dir makes that raise AFTER the
    file has been written. Relaxing relative_to keeps the redirection from depending on a cosmetic
    line, and is preferable to writing the scratch output inside the working tree."""

    def relative_to(self, *args, **kwargs):
        try:
            return Path.relative_to(self, *args, **kwargs)
        except ValueError:
            return self


def load_generator(root: Path, name: str):
    """Import the generator FROM THE TREE UNDER TEST. Its ROOT is `Path(__file__).parents[2]`, and it
    reads design/unlock_enums.json and several producer scripts at module level, so importing the
    copy that lives under `root` is what makes --root work at all — patching ROOT afterwards would be
    too late for those module-level reads."""
    path = root / "scripts" / "contracts" / f"{name}.py"
    if not path.exists():
        raise FileNotFoundError(path)
    spec = importlib.util.spec_from_file_location(f"_gen_{name}", path)
    mod = importlib.util.module_from_spec(spec)  # type: ignore[arg-type]
    sys.modules[spec.name] = mod  # type: ignore[union-attr]
    with contextlib.redirect_stdout(_Sink()):
        spec.loader.exec_module(mod)  # type: ignore[union-attr]
    return mod


def run_generator(mod, argv: list[str], **overrides) -> tuple[int, str]:
    """Call the generator's main() with its output constants redirected, then put them back."""
    saved = {k: getattr(mod, k) for k in overrides}
    saved_argv = sys.argv
    for k, v in overrides.items():
        setattr(mod, k, v)
    sys.argv = argv
    buf = _Sink()
    try:
        with contextlib.redirect_stdout(buf):
            rc = mod.main()
    finally:
        sys.argv = saved_argv
        for k, v in saved.items():
            setattr(mod, k, v)
    return rc, buf.getvalue()


MAX_DIFFS_PER_FILE = 4


def json_diff(a, b, path: str = "", acc: list[str] | None = None) -> list[str]:
    """Differing key paths between two JSON documents, in a form a human can act on.

    Deliberately collects several rather than stopping at the first: _shapes.json unions 23 entities
    in one file, and the first difference alphabetically hid a second, unrelated staleness during
    this validator's own bring-up (a kanji-directory sidecar masked a speak_path count that had moved
    from 275 to 274 four commits earlier)."""
    if acc is None:
        acc = []
    if len(acc) >= MAX_DIFFS_PER_FILE:
        return acc
    if type(a) is not type(b):
        acc.append(f"{path or '(root)'}: type {type(a).__name__} -> {type(b).__name__}")
    elif isinstance(a, dict):
        for k in a:
            if k not in b:
                acc.append(f"{path}.{k}: present in committed, absent from regenerated")
        for k in b:
            if k not in a:
                acc.append(f"{path}.{k}: absent from committed, present in regenerated")
        for k in a:
            if k in b:
                json_diff(a[k], b[k], f"{path}.{k}", acc)
    elif isinstance(a, list):
        if len(a) != len(b):
            acc.append(f"{path}: {len(a)} items committed, {len(b)} regenerated")
        else:
            for i, (x, y) in enumerate(zip(a, b)):
                json_diff(x, y, f"{path}[{i}]", acc)
    elif a != b:
        acc.append(f"{path or '(root)'}: {json.dumps(a, ensure_ascii=False)[:70]} -> "
                   f"{json.dumps(b, ensure_ascii=False)[:70]}")
    return acc[:MAX_DIFFS_PER_FILE]


def compare_file(committed: Path, regenerated: Path, label: str, fails: list[str]) -> None:
    if not committed.exists():
        fails.append(f"{label}: committed file is missing ({committed.name}) — run the generator")
        return
    if not regenerated.exists():
        fails.append(f"{label}: the generator did not produce it — the entity has fallen out of the "
                     f"generator's family list")
        return
    if committed.read_bytes() == regenerated.read_bytes():
        return
    detail = ""
    if committed.suffix == ".json":
        try:
            detail = " · ".join(json_diff(json.loads(committed.read_text(encoding="utf-8")),
                                          json.loads(regenerated.read_text(encoding="utf-8")))) \
                     or "byte-level difference with no structural diff (whitespace or key order)"
        except json.JSONDecodeError as e:
            detail = f"unparseable: {e}"
    else:
        ca = committed.read_text(encoding="utf-8").splitlines()
        rb = regenerated.read_text(encoding="utf-8").splitlines()
        for i, (x, y) in enumerate(zip(ca, rb), 1):
            if x != y:
                detail = f"line {i}: {x.strip()[:70]!r} -> {y.strip()[:70]!r}"
                break
        else:
            detail = f"{len(ca)} lines committed, {len(rb)} regenerated"
    fails.append(f"{label}: committed content differs from a fresh regeneration — {detail}")


# W06 release identity. These two, and only these two, may differ between the committed manifest
# and a fresh regeneration. Everything else in `build` is data-derived and must match.
IGNORED_MANIFEST_KEYS = ("date", "git_head")


def compare_manifest(committed: Path, regenerated: Path, label: str, fails: list[str]) -> None:
    """Like compare_file, with the two release-identity stamps redacted from both sides.

    Redacting a field from a freshness check is how a freshness check dies, so the redaction is as
    narrow as it can be: two scalars, named here, inside one block. `build.entities` stays under
    the exact diff — it is the half that says WHICH corpus this catalogue describes, and a stale
    hash there is the failure the block was added for. Key ORDER is still compared (no sort_keys),
    so a generator that starts emitting the same values differently is still caught.
    """
    if not committed.exists():
        fails.append(f"{label}: committed file is missing ({committed.name}) — run the generator")
        return
    if not regenerated.exists():
        fails.append(f"{label}: the generator did not produce it")
        return
    if committed.read_bytes() == regenerated.read_bytes():
        return
    try:
        a = json.loads(committed.read_text(encoding="utf-8"))
        b = json.loads(regenerated.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        fails.append(f"{label}: unparseable: {exc}")
        return
    ignored: list[str] = []
    for doc in (a, b):
        build = doc.get("build") if isinstance(doc, dict) else None
        if isinstance(build, dict):
            for k in IGNORED_MANIFEST_KEYS:
                if build.pop(k, None) is not None:
                    ignored.append(k)
    dump = lambda d: json.dumps(d, ensure_ascii=False, indent=2)  # noqa: E731
    if dump(a) == dump(b):
        return
    detail = " · ".join(json_diff(a, b)) or "byte-level difference with no structural diff"
    fails.append(f"{label}: committed content differs from a fresh regeneration — {detail} "
                 f"(build.{{{', '.join(IGNORED_MANIFEST_KEYS)}}} exempt)")


def count_records(root: Path, glob: str | None, packing: str) -> int | None:
    """Recount an entity straight from its declared glob, the way the manifest claims it can be."""
    if not glob:
        return None
    total = 0
    for path in sorted(root.glob(glob)):
        data = json.loads(path.read_text(encoding="utf-8"))
        if packing == "map":
            total += len(data) if isinstance(data, dict) else 0
        elif packing == "single":
            total += 1
        else:
            total += len(data) if isinstance(data, list) else 0
    return total


def declared_property_names(node, acc: set[str], refs: set[str] | None = None) -> None:
    """Every property name the schema names anywhere — properties, patternProperties values, items,
    allOf branches, $defs — plus the names of the shared $defs it points at. Used to prove the
    hand-authored schemas still cover their data.

    The $ref collection matters: kana_family declares `label` as
    `common.schema.json#/$defs/LocaleText`, so the literal key "pt-BR" in the data is described by
    common.schema.json and by nothing in the entity file. Ignoring that reports every localized
    string as an undescribed field."""
    if isinstance(node, dict):
        for k, v in node.items():
            if k == "properties" and isinstance(v, dict):
                acc.update(v)
            if k == "$ref" and isinstance(v, str) and refs is not None and "#/$defs/" in v:
                refs.add(v.split("#/$defs/", 1)[1].split("/")[0])
            declared_property_names(v, acc, refs)
    elif isinstance(node, list):
        for v in node:
            declared_property_names(v, acc, refs)


def data_object_keys(node, acc: set[str], depth: int = 0) -> None:
    """Object keys used by the DATA, skipping the top-level map keys (those are ids, not fields)."""
    if isinstance(node, dict):
        for k, v in node.items():
            if depth > 0:
                acc.add(k)
            data_object_keys(v, acc, depth + 1)
    elif isinstance(node, list):
        for v in node:
            data_object_keys(v, acc, depth)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=str(ROOT), help="repo root to validate (default: this repo)")
    args = ap.parse_args()
    root = Path(args.root).resolve()
    contracts = root / "contracts"
    fails: list[str] = []
    checked = 0

    try:
        gens = {n: load_generator(root, n) for n in GENERATORS}
    except FileNotFoundError as e:
        print(f"  FAIL cannot import the contract generators: {e} is missing")
        print("\nvalidate_schema_generation_is_current: FAIL 1 (generators unavailable)")
        return 1
    handwritten = set(getattr(gens["build_schemas"], "HANDWRITTEN", ()))
    runtime_entities = set(getattr(gens["build_schemas"], "RUNTIME", ()))
    runtime_dir = getattr(gens["build_schemas"], "RUNTIME_DIR", "user_state")

    def committed_paths(base: Path) -> dict[str, Path]:
        """entity -> its schema file, across both the flat content dir and the runtime subdirectory."""
        found = [*base.glob("*.schema.json"), *base.glob("*/*.schema.json")]
        return {p.stem.split(".")[0]: p for p in found if p.name != "common.schema.json"}

    def mirror(src_root: Path, dst_root: Path) -> None:
        """Copy every contract into a scratch tree, keeping the runtime subdirectory."""
        for p in [*src_root.glob("*.schema.json"), *src_root.glob("*/*.schema.json")]:
            dst = dst_root / p.relative_to(src_root)
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, dst)

    with tempfile.TemporaryDirectory(prefix="yomineko-contracts-") as tmpname:
        tmp = Path(tmpname)
        shapes_dir, schema_dir, manifest_dir = tmp / "shapes", tmp / "schemas", tmp / "manifest"
        for d in (shapes_dir, schema_dir, manifest_dir):
            d.mkdir()

        # 1 — _shapes.json is current -------------------------------------------------------------
        rc, _ = run_generator(gens["infer_shapes"], ["infer_shapes.py"],
                              OUT=_OutPath(shapes_dir / "_shapes.json"))
        if rc not in (0, 1):
            fails.append(f"infer_shapes.py exited {rc}")
        compare_file(contracts / "_shapes.json", shapes_dir / "_shapes.json",
                     "contracts/_shapes.json", fails)
        checked += 1

        # 2/3 — the generated schemas, from the COMMITTED shapes ----------------------------------
        # Deliberately built from the committed _shapes.json, not the freshly inferred one, so a
        # stale _shapes.json is reported once by check 1 instead of cascading into 21 schema diffs.
        bs = gens["build_schemas"]
        # build_schemas refuses to run unless the hand-authored schemas are already present in its
        # output directory (it asserts them rather than trusting a `continue` deep in the loop), so
        # seed the temp dir with the committed copies. They are then expected NOT to be rewritten —
        # check 3 below is what proves the generator left them alone.
        committed_schemas = committed_paths(contracts)
        seeded = {}
        for entity in sorted(handwritten):
            src = committed_schemas.get(entity)
            if src and src.exists():
                dst = schema_dir / src.relative_to(contracts)
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)
                seeded[entity] = dst.read_bytes()
        rc, _ = run_generator(bs, ["build_schemas.py"],
                              OUT=schema_dir, SHAPES=contracts / "_shapes.json")
        if rc != 0:
            fails.append(f"build_schemas.py exited {rc} — see its stderr; the contracts cannot be "
                         f"regenerated at all, so nothing below could be diffed")
        regenerated = {p.stem.split(".")[0]: p for p in schema_dir.glob("*.schema.json")
                       if p.stem.split(".")[0] not in handwritten}
        for entity, path in sorted(regenerated.items()):
            compare_file(contracts / path.name, path, f"contracts/{path.name}", fails)
            checked += 1
        for entity in sorted(set(committed_schemas) - set(regenerated) - handwritten
                             - {"common"}):
            fails.append(f"contracts/{entity}.schema.json: committed but no longer generated — either "
                         f"the entity left infer_shapes.FAMILIES or the file is an orphan")

        # 3 — the hand-authored schemas must come through untouched (the two map-packed content
        # entities, plus the seven runtime contracts under contracts/user_state/)
        for entity in sorted(handwritten):
            checked += 1
            expected = (f"contracts/{runtime_dir}/{entity}.schema.json" if entity in runtime_entities
                        else f"contracts/{entity}.schema.json")
            if entity not in committed_schemas:
                fails.append(f"{expected}: hand-authored schema is missing")
            elif (schema_dir / committed_schemas[entity].relative_to(contracts)).read_bytes() \
                    != seeded[entity]:
                fails.append(f"{entity}: build_schemas.py OVERWROTE a hand-authored schema — the guard "
                             f"that keeps generation from narrowing it no longer holds")

        # 3b — a runtime entity must NOT be measurable. Its name appearing in _shapes.json means
        # records were committed for an entity contracted to have none, and the next regeneration
        # would replace the hand-authored contract with whatever those records look like.
        checked += 1
        shapes_doc = json.loads((contracts / "_shapes.json").read_text(encoding="utf-8")) \
            if (contracts / "_shapes.json").exists() else {"entities": {}}
        leaked = sorted(runtime_entities & set(shapes_doc.get("entities", {})))
        if leaked:
            fails.append(f"runtime entities {leaked} appear in contracts/_shapes.json — records exist "
                         f"for an entity design/user_state.md contracts as record-free")

        # 4 — every FAMILIES entity has a schema (F15's map blind spot) ---------------------------
        families = [f["entity"] for f in getattr(gens["infer_shapes"], "FAMILIES", [])]
        for entity in families:
            if entity not in committed_schemas:
                fails.append(f"{entity}: declared in infer_shapes.FAMILIES but has no "
                             f"contracts/{entity}.schema.json — it is invisible to validate_contracts "
                             f"and absent from contracts/manifest.json, with no error anywhere")
        checked += 1

        # 5 — manifest.json + types.ts, rebuilt from the COMMITTED schemas -------------------------
        mirror(contracts, manifest_dir)
        rc, _ = run_generator(gens["build_manifest"], ["build_manifest.py"], CONTRACTS=manifest_dir)
        if rc != 0:
            fails.append(f"build_manifest.py exited {rc}")
        compare_manifest(contracts / "manifest.json", manifest_dir / "manifest.json",
                         "contracts/manifest.json", fails)
        compare_file(contracts / "types.ts", manifest_dir / "types.ts", "contracts/types.ts", fails)
        checked += 2

    # 6 — manifest counts against a live recount --------------------------------------------------
    manifest_path = contracts / "manifest.json"
    if manifest_path.exists():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        for e in manifest.get("entities", []):
            actual = count_records(root, e.get("files"), e.get("packing") or "list")
            declared_records = e.get("records")
            cls = e.get("class", "content")
            checked += 1
            # The runtime class (design/user_state.md §12) is the ONE case where null files and null
            # records are correct: those records are minted per learner and none is committed here.
            # The exemption is granted on the declared class, and it is policed in both directions —
            # a runtime row carrying a glob fails even though the glob matches nothing, which is what
            # stops a content entity whose exporter stopped from relabelling itself and going quiet.
            if cls == "runtime":
                if e.get("files") is not None or e.get("packing") is not None:
                    fails.append(f"manifest {e['entity']}: class 'runtime' but it declares files "
                                 f"{e.get('files')!r} (matching {actual} record(s)) / packing "
                                 f"{e.get('packing')!r}. A runtime entity holds no committed records; "
                                 f"an entity with data is content and must be counted like one.")
                if declared_records is not None:
                    fails.append(f"manifest {e['entity']}: class 'runtime' but declares "
                                 f"{declared_records} records — nothing measured it, so the count is "
                                 f"an assertion nobody can check")
                if e["entity"] not in runtime_entities:
                    fails.append(f"manifest {e['entity']}: class 'runtime' but it is not in "
                                 f"build_schemas.RUNTIME, so build_schemas.py would regenerate and "
                                 f"narrow its hand-authored contract")
                continue
            if actual is None:
                fails.append(f"manifest {e['entity']}: class {cls!r} declares no `files` glob — the "
                             f"catalogue cannot be used to locate its data. Only class 'runtime' may "
                             f"have none.")
            elif actual == 0:
                fails.append(f"manifest {e['entity']}: its glob {e.get('files')!r} matches 0 records "
                             f"— the data moved and every count downstream is now fiction")
            elif declared_records is None:
                # `records` is copied from the schema's x-yomineko, which infer_shapes measures. The
                # two map-packed entities have HAND-AUTHORED schemas that measure nothing, so a null
                # count there is the designed state, not drift — the glob floor above still holds
                # them to a live data check. Any OTHER entity with a null count means the measured
                # block went missing.
                if e["entity"] not in handwritten:
                    fails.append(f"manifest {e['entity']}: declares no record count, and its schema is "
                                 f"generated — x-yomineko.records has gone missing")
            elif declared_records != actual:
                fails.append(f"manifest {e['entity']}: declares {declared_records} records, the glob "
                             f"{e.get('files')!r} holds {actual}")
    else:
        fails.append("contracts/manifest.json is missing")

    # 7 — the hand-authored schemas still describe their data --------------------------------------
    for entity, data_rel in (("capability_lesson_map", "corpus/capabilities/lesson_map.json"),
                             ("kana_family", "corpus/kana/families.json")):
        schema_path, data_path = contracts / f"{entity}.schema.json", root / data_rel
        checked += 1
        if not schema_path.exists() or not data_path.exists():
            continue
        declared: set[str] = set()
        refs: set[str] = set()
        declared_property_names(json.loads(schema_path.read_text(encoding="utf-8")), declared, refs)
        common_path = contracts / "common.schema.json"
        if refs and common_path.exists():
            common_defs = json.loads(common_path.read_text(encoding="utf-8")).get("$defs", {})
            for name in sorted(refs):
                if name in common_defs:
                    declared_property_names(common_defs[name], declared, refs=None)
        used: set[str] = set()
        data_object_keys(json.loads(data_path.read_text(encoding="utf-8")), used)
        undescribed = sorted(used - declared)
        if undescribed:
            fails.append(f"{entity}: {data_rel} uses field(s) {undescribed} that the hand-authored "
                         f"schema does not declare — it is not regenerated, so the edit must be made "
                         f"by hand")

    for f in fails[:MAX_FAILS]:
        print("  FAIL", f)
    if len(fails) > MAX_FAILS:
        print(f"  … {len(fails) - MAX_FAILS} more")
    print(f"\nvalidate_schema_generation_is_current: {checked} contract artifacts checked, "
          f"{'FAIL ' + str(len(fails)) if fails else 'ALL OK'}")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
