#!/usr/bin/env python3
"""Gate: prototype/app/data/ is the CURRENT projection of the corpus, at the CURRENT build.

WHY THIS EXISTS (review finding F11, extended by W41)
----------------------------------------------------
The product does not ship `corpus/` and `course/`; it ships the consolidated JSON files under
`prototype/app/data/`, generated by `prototype/scripts/sync-data.mjs` and COMMITTED. A grep of
scripts/validate/*.py for "prototype" used to return exactly one hit — a comment. So the derived
copies the app actually reads were validated by nothing: edit a lesson body, forget to run
`npm run sync-data`, and every gate in the suite still passed while the app served last month's
text. prototype/README.md stated the rule and left a human to remember it.

HOW IT CHECKS
-------------
Two independent nets, because a stale sync shows up in two ways.

(1) CONTENT — this validator RE-DERIVES every output in Python and deep-compares it against the
    committed file. Like sync-data.mjs, the re-derivation is driven by `contracts/manifest.json`:
    the same globs, the same `packing`, the same `stable_id_field`/`natural_key` addressing, the
    same record counts. Nothing about where the data lives is restated here, so the two sides can
    no longer drift apart by editing one glob; what IS restated is the read model — the joins and
    the deliberate slimming (`_slim_sentence`, `_slim_reading`) — which is the point: the
    projection is a contract, not a side effect. An undocumented omission fails, and so does an
    extra field, a stale record and a stale id set.

(2) BUILD IDENTITY — `app/data/_build.json` must carry contracts/manifest.json's `build` block
    verbatim: date, git_head and the per-entity content hashes. Re-export the corpus, regenerate
    the manifest, and forget the sync, and the hashes disagree even before a single record is
    compared. A stale sync is detectable by hash, not by file count.

Reads the exported JSON only — never db/corpus.sqlite.

Usage: validate_prototype_sync.py [--root PATH] [--list N]
Exit 1 on any difference; the fix is `cd prototype && npm run sync-data`.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
REPO_ROOT = Path(__file__).resolve().parents[2]

# The published data roots the prototype builds from (mjs DATA_ROOTS). A content entity whose glob
# points outside them — today only `review_ledger`, under research/derived/ — is out of the app's
# input tree and is not synced.
DATA_ROOTS = ("corpus/", "course/")

# The entities the read model consumes. Anything else the manifest lists is loaded and checked, but
# does not reach app/data yet.
CONSUMED = ("course_manifest", "course", "topic", "lesson", "kanji", "vocab", "grammar", "sentence",
            "reading", "stroke_order", "stroke_lines", "stroke_kana", "kana_family", "exam_item",
            "exercise_conjugation", "exercise_role", "speak_path", "speak_unit")

BUILD_FILE = "_build.json"


class SyncError(Exception):
    """A manifest promise the data does not keep — reported as a FAIL, never a traceback."""


# --------------------------------------------------------------------------- manifest glob resolution
def _segment_re(segment: str) -> re.Pattern[str]:
    """One path segment of a manifest glob -> regex. Supports `*` and `[...]`/`[!...]`; no `**`."""
    src = ""
    i = 0
    while i < len(segment):
        c = segment[i]
        if c == "*":
            src += "[^/]*"
        elif c == "?":
            src += "[^/]"
        elif c == "[":
            j = i + 1
            negated = False
            if j < len(segment) and segment[j] in "!^":
                negated = True
                j += 1
            cls = ""
            while j < len(segment) and segment[j] != "]":
                cls += segment[j]
                j += 1
            if j >= len(segment):
                raise SyncError(f'unterminated [...] in manifest glob segment "{segment}"')
            src += f"[{'^' if negated else ''}{cls}]"
            i = j
        else:
            src += re.escape(c)
        i += 1
    return re.compile(f"^{src}$")


def _resolve_glob(root: Path, glob: str) -> list[Path]:
    """Resolve a manifest `files` glob under `root` into a sorted list of paths."""
    current = [root]
    for segment in glob.split("/"):
        rx = _segment_re(segment)
        nxt: list[Path] = []
        for d in current:
            if not d.is_dir():
                continue
            for child in d.iterdir():
                if rx.match(child.name):
                    nxt.append(child)
        current = nxt
    return sorted(current)


# --------------------------------------------------------------------------- manifest-driven loading
def _read_json(p: Path) -> Any:
    return json.loads(p.read_text(encoding="utf-8"))


class Entity:
    """One loaded content entity: its per-file groups, its flat records, its address index."""

    def __init__(self, spec: dict, root: Path) -> None:
        self.spec = spec
        self.name: str = spec["entity"]
        files = _resolve_glob(root, spec["files"])
        if not files:
            raise SyncError(f'{self.name}: manifest glob "{spec["files"]}" matched no file')
        packing = spec["packing"]
        self.groups: list[tuple[str, list]] = []
        self.records: list = []
        self.map: dict | None = None
        for f in files:
            data = _read_json(f)
            if packing == "list":
                if not isinstance(data, list):
                    raise SyncError(f"{self.name}: {f.name} is packed 'list' but is not an array")
                self.groups.append((f.stem, data))
                self.records.extend(data)
            elif packing == "single":
                if isinstance(data, list):
                    raise SyncError(f"{self.name}: {f.name} is packed 'single' but is an array")
                self.groups.append((f.stem, [data]))
                self.records.append(data)
            elif packing == "map":
                if not isinstance(data, dict):
                    raise SyncError(f"{self.name}: {f.name} is packed 'map' but is not an object")
                if self.map is not None:
                    raise SyncError(f"{self.name}: packing 'map' matched more than one file")
                self.map = data
                self.groups.append((f.stem, []))
            else:
                raise SyncError(f'{self.name}: unknown packing "{packing}"')

        want = spec.get("records")
        if want is not None and packing != "map" and len(self.records) != want:
            raise SyncError(f"{self.name}: manifest declares {want} records, the glob yields "
                            f"{len(self.records)}")

        natural = spec.get("natural_key")
        key_field = spec.get("stable_id_field") or (natural if natural and "," not in natural else None)
        self.key_field: str | None = key_field
        self.by_id: dict = {}
        if key_field and packing != "map":
            for r in self.records:
                k = r.get(key_field)
                if k is None:
                    raise SyncError(f'{self.name}: a record has no "{key_field}"')
                if k in self.by_id:
                    raise SyncError(f"{self.name}: two records share the address {k!r}")
                self.by_id[k] = r


def load_entities(root: Path, manifest: dict) -> dict[str, Entity]:
    out: dict[str, Entity] = {}
    for spec in manifest["entities"]:
        if spec["class"] == "runtime":
            continue
        if not spec.get("files"):
            raise SyncError(f'{spec["entity"]}: class "content" with no files glob')
        if not any(spec["files"].startswith(r) for r in DATA_ROOTS):
            continue
        out[spec["entity"]] = Entity(spec, root)
    return out


# --------------------------------------------------------------------------- mjs helper ports
def _pick(src: dict, keys: tuple[str, ...]) -> dict:
    """JSON.stringify drops keys whose value is `undefined`; an absent source key must stay absent."""
    return {k: src[k] for k in keys if k in src}


def _pt(v: Any) -> Any:
    """Port of pt() in the mjs: locale-object -> pt-BR, else en, else ""."""
    if isinstance(v, dict):
        r = v.get("pt-BR")
        if r is None:
            r = v.get("en")
        return "" if r is None else r
    if isinstance(v, list):
        return ""          # a non-locale object has neither key -> "" in JS too
    return "" if v is None else v


_ROMAJI_PUNCT = re.compile(r"\s+([?!,.;:、。？！])")


def _spaced_romaji(s: dict) -> str:
    """Port of spacedRomaji: rebuild space-separated romaji from the per-token romaji."""
    toks = [t.get("romaji") for t in (s.get("tokens") or []) if isinstance(t, dict) and t.get("romaji")]
    if not toks:
        return s.get("romaji") or ""
    return _ROMAJI_PUNCT.sub(r"\1", " ".join(toks)).strip()


def _slim_token(t: dict) -> dict:
    o = {}
    for src, dst in (("surface", "s"), ("reading", "r"), ("romaji", "ro"), ("pos", "pos")):
        if src in t:
            o[dst] = t[src]
    o["gloss"] = _pt(t.get("gloss"))
    o["role"] = _pt(t.get("role"))
    return o


def _slim_particle(p: dict) -> dict:
    o = {}
    for src, dst in (("particle", "p"), ("function_type", "ft")):
        if src in p:
            o[dst] = p[src]
    o["fn"] = _pt(p.get("function"))
    o["ex"] = _pt(p.get("explanation"))
    return o


def _slim_sentence(s: dict) -> dict:
    """Display fields + grammar tags + the token/particle dissection; heavy analysis dropped."""
    o = _pick(s, ("slug", "jp", "kana"))
    o["romaji"] = _spaced_romaji(s)
    o.update(_pick(s, ("translation", "translation_literal", "structure_explanation", "level")))
    o["grammar"] = s.get("grammar") or []
    o["tokens"] = [_slim_token(t) for t in (s.get("tokens") or [])]
    o["particles"] = [_slim_particle(p) for p in (s.get("particles") or [])]
    return o


def _slim_reading(r: dict) -> dict:
    o = _pick(r, ("slug", "jp", "title", "translation"))
    o["tokens"] = [_pick(t, ("s", "r", "ro", "pos")) for t in (r.get("tokens") or [])]
    o.update(_pick(r, ("length_band",)))
    o["source_slugs"] = r.get("source_slugs") or []
    return o


# --------------------------------------------------------------------------- the read model
def _by_level(name: str, records: list) -> dict:
    out: dict = {}
    for r in records:
        if not r.get("level"):
            raise SyncError(f'{name}: a record has no "level" to group by')
        out.setdefault(r["level"], []).append(r)
    return out


def build_read_model(ent: dict[str, Entity]) -> dict[str, Any]:
    """Re-run sync-data.mjs's read model in Python. Returns {output filename: value}."""
    def get(name: str) -> Entity:
        if name not in ent:
            raise SyncError(f'entity "{name}" is missing from contracts/manifest.json')
        return ent[name]

    out: dict[str, Any] = {}

    # ---- courseware: the course manifest joined to course/topic/lesson records BY ID (no paths).
    course_manifest = get("course_manifest").records[0]
    course_by_id, topic_by_id, lesson_by_id = get("course").by_id, get("topic").by_id, get("lesson").by_id
    courses: dict = {}
    topics: dict = {}
    for c in course_manifest["courses"]:
        course = course_by_id.get(c["id"])
        if course is None:
            raise SyncError(f'course_manifest points at {c["id"]}, which no course record claims')
        topic_stubs = []
        for t in course.get("topics") or []:
            topic = topic_by_id.get(t["id"])
            if topic is None:
                raise SyncError(f'course {c["id"]} points at topic {t["id"]}, which no topic record claims')
            lesson_stubs = []
            for lstub in topic.get("lessons") or []:
                leaf = lesson_by_id.get(lstub["id"])
                if leaf is None:
                    raise SyncError(f'topic {t["id"]} points at lesson {lstub["id"]}, which no lesson record claims')
                lesson_stubs.append({"id": leaf["id"], "order": leaf.get("order"),
                                     **_pick(lstub, ("title", "description", "needs", "unlocks"))})
            topics[t["id"]] = {"id": t["id"],
                               **_pick(topic, ("level", "order", "title", "theme", "objectives")),
                               **_pick(t, ("unlocks_summary",)), "lessons": lesson_stubs}
            topic_stubs.append({"id": t["id"],
                                **_pick(t, ("order", "title", "theme", "lesson_count", "unlocks_summary")),
                                "lessons": [x["id"] for x in lesson_stubs]})
        courses[c["id"]] = {**_pick(c, ("id", "level", "order", "title", "topic_count", "lesson_count")),
                            **_pick(course, ("overview",)), "topics": topic_stubs}
    out["courses.json"] = courses
    out["topics.json"] = topics
    out["lessons.json"] = lesson_by_id

    # ---- registries, keyed by the manifest's address field, shipped whole.
    out["kanji.json"] = get("kanji").by_id
    out["vocab.json"] = get("vocab").by_id
    out["grammar.json"] = get("grammar").by_id

    # ---- stroke data: three separate entities, so no shape-sniffing splits them any more.
    out["strokes.json"] = get("stroke_order").by_id
    out["kanaStrokes.json"] = get("stroke_kana").by_id
    out["strokeLines.json"] = {ch: _pick(rec, ("strokes",))
                               for ch, rec in get("stroke_lines").by_id.items()}

    # ---- the kana syllabary chart: a keyed collection, copied through verbatim.
    out["kana.json"] = get("kana_family").map

    # ---- sentences + readings, slimmed.
    out["sentences.json"] = {k: _slim_sentence(s) for k, s in get("sentence").by_id.items()}
    out["readings.json"] = {k: _slim_reading(r) for k, r in get("reading").by_id.items()}

    # ---- exam banks: level -> type -> items. `type` is the source basename after "n<digit>_",
    # which is what the manifest glob corpus/exam_banks/n[0-9]_*.json enumerates.
    exam: dict = {}
    for basename, items in get("exam_item").groups:
        m = re.fullmatch(r"(n[0-9])_(.+)", basename)
        if not m:
            raise SyncError(f"exam_item: {basename}.json does not match the glob's n<digit>_<type> shape")
        for it in items:
            if it.get("level") != m.group(1):
                raise SyncError(f'exam_item {it.get("id")}: level "{it.get("level")}" filed in {basename}.json')
        if items:
            exam.setdefault(m.group(1), {})[m.group(2)] = items
    out["examBanks.json"] = exam

    # ---- drill banks: grouped by each record's own `level`, no filename parsing.
    out["conjugationBank.json"] = _by_level("exercise_conjugation", get("exercise_conjugation").records)
    out["roleBank.json"] = _by_level("exercise_role", get("exercise_role").records)

    # ---- the speaking path: the stage record plus every unit, keyed by stable id, in stage order.
    speak = dict(get("speak_path").records[0])
    unit_by_id = get("speak_unit").by_id
    units: dict = {}
    for stage in speak.get("stages") or []:
        for uid in stage.get("unit_ids") or []:
            u = unit_by_id.get(uid)
            if u is None:
                raise SyncError(f'speak stage {stage.get("slug")} claims unit {uid}, which no record provides')
            units[uid] = u
    for uid in unit_by_id:
        if uid not in units:
            raise SyncError(f"speak_unit {uid} is claimed by no stage")
    speak["units"] = units
    out["speakPath.json"] = speak
    return out


# --------------------------------------------------------------------------- build identity
def expected_build(manifest: dict, model: dict[str, Any]) -> dict[str, Any]:
    """What app/data/_build.json must contain, derived from the manifest the same way the mjs does."""
    namespaces = {s["entity"]: s["id_namespace"][0] for s in manifest["entities"]
                  if isinstance(s.get("id_namespace"), list) and len(s["id_namespace"]) == 1}
    return {
        "manifest_schema_version": manifest["schema_version"],
        "date": manifest["build"]["date"],
        "git_head": manifest["build"]["git_head"],
        "entities": manifest["build"]["entities"],
        "namespaces": namespaces,
        "outputs": {name: {"records": _record_count(name, value)} for name, value in model.items()},
    }


def check_build(got: Any, want: dict[str, Any], out: list[str]) -> None:
    """Compare _build.json field by field, naming the drifted entity hashes explicitly."""
    if not isinstance(got, dict):
        out.append(f"{BUILD_FILE}: not an object")
        return
    for key in ("manifest_schema_version", "date", "git_head"):
        if got.get(key) != want[key]:
            out.append(f"{BUILD_FILE}.{key}: app/data={_short(got.get(key))} manifest={_short(want[key])}")
    for key in ("entities", "namespaces", "outputs"):
        g, w = got.get(key), want[key]
        if not isinstance(g, dict):
            out.append(f"{BUILD_FILE}.{key}: missing or not an object")
            continue
        for name in sorted(set(g) | set(w), key=str):
            if name not in g:
                out.append(f"{BUILD_FILE}.{key}.{name}: missing in app/data (stale sync)")
            elif name not in w:
                out.append(f"{BUILD_FILE}.{key}.{name}: in app/data but not in the manifest")
            elif g[name] != w[name]:
                label = "content hash" if key == "entities" else key
                out.append(f"{BUILD_FILE}.{key}.{name}: {label} app/data={_short(g[name])} "
                           f"manifest={_short(w[name])}")


# --------------------------------------------------------------------------- comparison
def _diff(want: Any, got: Any, path: str, out: list[str], cap: int) -> None:
    """Collect up to `cap` differences as json-path strings. `want` = re-derived, `got` = committed."""
    if len(out) >= cap:
        return
    if isinstance(want, dict) and isinstance(got, dict):
        for k in sorted(set(want) | set(got), key=str):
            if len(out) >= cap:
                return
            if k not in got:
                out.append(f"{path}.{k}: missing in app/data (stale sync)")
            elif k not in want:
                out.append(f"{path}.{k}: present in app/data but not in the corpus projection")
            else:
                _diff(want[k], got[k], f"{path}.{k}", out, cap)
        return
    if isinstance(want, list) and isinstance(got, list):
        if len(want) != len(got):
            out.append(f"{path}: length {len(got)} in app/data, {len(want)} derived")
            return
        for i, (a, b) in enumerate(zip(want, got)):
            if len(out) >= cap:
                return
            _diff(a, b, f"{path}[{i}]", out, cap)
        return
    if want != got:
        out.append(f"{path}: app/data={_short(got)} derived={_short(want)}")


def _short(v: Any) -> str:
    s = json.dumps(v, ensure_ascii=False) if not isinstance(v, str) else v
    return s if len(s) <= 70 else s[:67] + "..."


def _record_count(name: str, v: Any) -> int:
    """Records, not top-level keys — so the printed numbers are the ones F11 measured by hand
    (examBanks 6048, roleBank 5358, conjugationBank 18524, speakPath 72 units)."""
    if name == "examBanks.json":
        return sum(len(items) for by_type in v.values() for items in by_type.values())
    if name in ("conjugationBank.json", "roleBank.json"):
        return sum(len(items) for items in v.values())
    if name == "speakPath.json":
        return len(v.get("units", {}))
    return len(v) if isinstance(v, (dict, list)) else 1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(REPO_ROOT), help="tree to validate (default: repo root)")
    ap.add_argument("--list", type=int, default=15, help="max FAIL lines to print")
    args = ap.parse_args()
    root = Path(args.root).resolve()
    data = root / "prototype" / "app" / "data"
    if not data.is_dir():
        print(f"FAIL validate_prototype_sync: {data} is MISSING — a gate whose data vanished must FAIL, not certify nothing")
        return 1
    manifest_path = root / "contracts" / "manifest.json"
    if not manifest_path.is_file():
        print(f"FAIL validate_prototype_sync: {manifest_path} is MISSING — the projection is derived from it")
        return 1

    manifest = _read_json(manifest_path)
    try:
        entities = load_entities(root, manifest)
        model = build_read_model(entities)
        want_build = expected_build(manifest, model)
    except SyncError as e:
        print(f"  FAIL {e}")
        print("\nvalidate_prototype_sync: FAIL — contracts/manifest.json and the exported data disagree; "
              "re-run the exporter and scripts/contracts/build_manifest.py")
        return 1

    outputs = tuple(model) + (BUILD_FILE,)
    fails: list[str] = []
    committed_names = {p.name for p in data.glob("*.json")}
    for extra in sorted(committed_names - set(outputs)):
        fails.append(f"{extra}: file in app/data that sync-data.mjs does not write (unvalidated)")

    rows: list[tuple[str, int, int, int]] = []
    for name in model:
        want = model[name]
        f = data / name
        if not f.exists():
            fails.append(f"{name}: missing from prototype/app/data")
            continue
        got = _read_json(f)
        d: list[str] = []
        _diff(want, got, name.removesuffix(".json"), d, 400)
        rows.append((name, _record_count(name, got), _record_count(name, want), len(d)))
        fails.extend(d)

    build_fails: list[str] = []
    bf = data / BUILD_FILE
    if not bf.exists():
        build_fails.append(f"{BUILD_FILE}: missing from prototype/app/data — the release identity is unrecorded")
    else:
        check_build(_read_json(bf), want_build, build_fails)
    fails.extend(build_fails)

    for r in fails[:args.list]:
        print("  FAIL", r)
    if len(fails) > args.list:
        print(f"  ... {len(fails) - args.list} more")
    print()
    for name, ngot, nwant, nd in rows:
        flag = "OK " if nd == 0 else "DIFF"
        print(f"  [{flag}] {name:<22} app/data {ngot:>6} / derived {nwant:>6}"
              + (f"  ({nd} diffs)" if nd else ""))
    print(f"  [{'OK ' if not build_fails else 'DIFF'}] {BUILD_FILE:<22} build {want_build['date']} @ "
          f"{want_build['git_head'][:8]}, {len(want_build['entities'])} entity hashes"
          + (f"  ({len(build_fails)} diffs)" if build_fails else ""))
    print(f"\nvalidate_prototype_sync: {len(rows)} files + {BUILD_FILE}, "
          f"{len(entities)} content entities from contracts/manifest.json "
          f"({len([e for e in entities if e not in CONSUMED])} loaded but not yet consumed), "
          + (f"FAIL {len(fails)} — run `cd prototype && npm run sync-data`" if fails else "ALL OK"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
